### ISSUE TITLE
Page indexer does not work properly with hidden gridelements

### ISSUE THREAD

**Issue by christianbltr** [teaminmedias-pluswerk/ke_search#104]
taken from https://forge.typo3.org/issues/65536

When creating content with gridelements and hiding the grid, the content inside the grid is still indexed by ke_search page indexer and appears in search results. This probably happens because only the grid is hidden but not the contents within the grid. When the grid AND the contained content is hidden, the page indexer works probably and does not index the hidden content.

In my opinion ke_search should not index the content within a hidden grid, even when the content itself is marked as hidden, because it is not shown in the frontend.

This bug has been observed with TYPO3 6.2.9, ke_search 1.8.4 and gridelements 3.1.0.

Steps to reproduce this issue:
- Create grid with gridelements
- Add content elements to grid
- Hide the grid (but not the content elements within the grid)
- Restart Indexing with ke_search page indexer
-> The content elements the grid will get indexed even though not visible in frontend

**Comment by a-r-m-i-n** [comment]
Also ke_search ignores the containers of gridelements, when sorting contents.

**Example content structure:**

- Grid (sorting: 64)
  - Content A (sorting: 8)
  - Content B (sorting: 16)
- Grid (sorting: 128)
  - Content C (sorting: 2)
  - Content D (sorting: 4)

Output in frontend is A, B, C, D - but ke_search's indexer will index C, D, A, B.

For searching purposes this does not matter. But when displaying preview text of page in search results, this may confuse the user.

**Comment by christianbltr** [comment]
Regarding the sorting I created a new issue:
https://github.com/teaminmedias-pluswerk/ke_search/issues/107

**Comment by a-r-m-i-n** [comment]
So, regarding the hidden issue... when I add this subselect to fields:
```
$fields .= ', (SELECT hidden FROM tt_content as t2 WHERE t2.uid = tt_content.tx_gridelements_container) as parentHidden'
```

![2017-05-19_1619](https://cloud.githubusercontent.com/assets/1275298/26251865/fa9a776a-3cae-11e7-891e-e2715dd2f820.png)


and check in foreach-loop if `$ttContentRow['parentGridHidden'] === '1'`, it works.

But if the parent grid container is located **inside** of a hidden container, it is not working, cause it's not recursive.

**Comment by creationell** [comment]
We experience the same issue again in TYPO3 9.5 (I guess because gridelements handles things differently now). Is this already a known bug or should I create a new issue/PR?

**Comment by christianbltr** [comment]
Yes, it would be great if you could create a new new issue.
