### ISSUE TITLE
Filter Selection in Flexform

### ISSUE THREAD

**Issue by ghost** [teaminmedias-pluswerk/ke_search#113]
I have a problem with the filter selections in the flexform of ke_search.
Already tried compatibilty7 but no change.

TYPO3 Version: 8.7.1
ke_search Version: latest master

Could you check this?

![image](https://cloud.githubusercontent.com/assets/13207673/26323079/ceff3b0a-3f2d-11e7-9a83-02a079ff1e9c.png)

**Comment by a-r-m-i-n** [comment]
I'll check this tomorrow. It could help me to reconstruct this issue when you would describe, what you exactly did, before this error occured. Thanks

**Comment by ghost** [comment]
I added a filter and a filteroption. Tagged a file in FAL with a new category named like the filteroption and indexed.
After that i added a new search form and the 3 Error messages appeared.
Doublechecked the index Table the filteroption or "tag" i created is in the table. So i think the indexing process itself is ok.

**Comment by a-r-m-i-n** [comment]
Should work with this patch. Also you can define several sysfolders in plugin and ke_search will display all filters/options in all configured sysfolders, now. Before this fix just the first set sysfolder worked.

**Comment by ghost** [comment]
Thanks a lot! I will check the patch until tomorrow.

Update:
Works like a charm. Thank you very much.
