### ISSUE TITLE
Refactor class names and locations

### ISSUE THREAD

**Issue by christianbltr** [teaminmedias-pluswerk/ke_search#117]
All classes should be namespaced.

All class names should be named and located as given in the codoing guidelines (https://docs.typo3.org/typo3cms/ExtbaseFluidBook/a-CodingGuidelines/Index.html#folder-structure)

Namespace should be "Pluswerk", not "TeaminmediasPluswerk" which is currently used in the Backend Module Controller.

**Comment by teaminmedias-pluswerk** [comment]
Fixed in branch compat9, will be in version 9.
But namespace stays: TeaminmediasPluswerk.
