### ISSUE TITLE
Remove pi3

### ISSUE THREAD

**Issue by christianbltr** [teaminmedias-pluswerk/ke_search#118]
The Plugin pi3 should be removed since it is not used anymore.

References to this plugin should be removed, eg. the corresponding filter type.

pi3 was the "multi selection" plugin. It was only available in version 1.X. It featured a multi-selection of filter options via checkboxes on a separate page.

**Comment by teaminmedias-pluswerk** [comment]
Fixed in branch compat9, will be in version 3.
