### ISSUE TITLE
Display searchword statistics in frontend

### ISSUE THREAD

**Issue by in-session** [teaminmedias-pluswerk/ke_search#122]
Hi, 

first of all, many thanks for the great extension. 
Isit possible to show the searchword statistics for the last 30 days in the frontend?
The idea is to show the most searched words of the last 30 days sorted by counter and a maximum list of 10 words.

Can you help me in this case?

Cheers Chris

**Comment by christianbltr** [comment]
Right now there's no such feature. Maybe in the futue...

**Comment by velletti** [comment]
@Chris / @in-session 

This should be done very fast with extension builder and reusing the tx_kesearch_stat_word table, adding a function to the domain Repositoy .

if you have problems with this, i can support you ..

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
