### ISSUE TITLE
Translation of Filter Options does not work

### ISSUE THREAD

**Issue by velletti** [teaminmedias-pluswerk/ke_search#124]
We have TYPO3 7.6.18 and KE_search 2.4.3 in 7 Languages.
As we need sometimes Website Content only in one language that does not exist in default language, we need to set in typoscript 

config.sys_language_overlay = 0 
sys_language_mode = strict

Creating localized Filters Options for different languages works, but in Frontend only default language is show. 

Reason looks for me in 
ke_search/Classes/lib/class.tx_kesearch_filters.php

	`
	   public function languageOverlay(array $rows, $table) {

		if(is_array($rows) && count($rows))  {

			foreach($rows as $key => $row) {

				if(is_array($row) && $GLOBALS['TSFE']->sys_language_contentOL ) {

					$row = $GLOBALS['TSFE']->sys_page->getRecordOverlay(`

changing typoscriot to config.sys_language_overlay = 1 helps, but we need this setting 

So: this function it will never try to getRecordOverlay ... 
changing the code like the example below helps

	`
	   public function languageOverlay(array $rows, $table) {

		if(is_array($rows) && count($rows))  {

			foreach($rows as $key => $row) {

				if(is_array($row) && $GLOBALS['TSFE']->sys_language_content ) {

					$row = $GLOBALS['TSFE']->sys_page->getRecordOverlay(`

( Just check if we are in a translated Version of the Website or if sys_language_content hat fallback to default language instead of the used language mode by removing the "OL"  in if condition **$GLOBALS['TSFE']->sys_language_contentOL** )

I can fork this reposity and create a pull request. but as i saw you pushed 3 hours ago to a feature branch, shall i do my change on master or on your actual feature ?

**Comment by a-r-m-i-n** [comment]
Hey! Thanks here again. Like in #125 described, a pull request would be very nice and just use master branch :)
