### ISSUE TITLE
Create Filter in "NON" default language does not work

### ISSUE THREAD

**Issue by velletti** [teaminmedias-pluswerk/ke_search#125]
We use TYPO3 with config.sys_language_mode = 0 
Creating a Filter just for a specific Language that  because this kind of elements do not exist in default language, i tried to create a filter only for italy. 

and get this error`
#1438185437: Type value from database record not defined in TCA of table tx_kesearch_filters and neither 0 nor 1 are defined as fallback. `

**Reason** is in my opinion the TCA config :
ke_search/Configuration/TCA/tx_kesearch_filters.php 

As CTRL -> Type uses the Column field "renderType" but Column "rendertyp" is defined to be not rendered in localized mode, this crashes .. 
```

   'ctrl' => array(
        'title' => 'LLL:EXT:ke_search/locallang_db.xml:tx_kesearch_filters',
         ... 
        'type' => 'rendertype',
         ...
```

**Solution**

Remove l10Mode setting for Field rendertype and add  a display Condition:

**Wrong:**
```
     'rendertyphave both :e' => array(
               'exclude' => 0,
               'l10n_mode' => 'exclude',
```

**Correct:**
```
   'rendertype' => array(
               'exclude' => 0,
              'displayCond' => 'FIELD:l10n_parent:<:1',
```

With this TCA setting i was able to have both: 

Translated Filters that have wrong (differing from default) Rendertype but it is not visible and also not setable, an Filters only i a non default language .

I can create a Fork / Pull request but should know if i shall fork the master or the feature branch you are actually woring on ..

**Comment by velletti** [comment]
Misadvantage of this change: 

if you switch the RenderType of default language, it is not synced anymore to the localized records. 

Possible Workaround
You need to re-localize them 
or
we do some changes to the get Filter Funktion ...

**Comment by velletti** [comment]
Adding the code below to 
ke_search/Classes/lib/class.tx_kesearch_filters.php

in : 
...
	public function languageOverlay(array $rows, $table) {
		
..
 after the $GLOBALS['TSFE']->sys_page->getRecordOverlay( 
... 	
   if( is_array($row)) {
	if( $table == "tx_kesearch_filters") {
             $row['rendertype'] = $rows[$key]['rendertype'] ;
        }
             $rows[$key] = $row;
        } else {
             unset( $rows[$key] ) ;
        }
...

The rendertype is taken from Default language

**Comment by a-r-m-i-n** [comment]
Hey! Thank you for this detailed description and fix!
A pull request would be very nice! Please use the master branch. This new feature branch branch will take a while... ;-)
