### ISSUE TITLE
Search page without query throws php warning 

### ISSUE THREAD

**Issue by velletti** [teaminmedias-pluswerk/ke_search#127]
foreach ($rows as $row) { 

But as $row is not an array, this throws a php warning. 

This just ugly in DEV mode but easy to be solved.  see comming pull request

**Comment by christianbltr** [comment]
I think this has been fixed with https://github.com/teaminmedias-pluswerk/ke_search/pull/126?
So I'm closing this issue.

**Comment by velletti** [comment]
Yes you are right. I forgot to add the "Fixes #127" to my Commits to issue 124 and 126 .. ..

BTW: Meine SlideShow auf dem T3C in München zu KE Search um eigenen Indexer erweitern. Falls es einer von euch mal irgendwo anders auf einem Camp halten will .. 
https://docs.google.com/presentation/d/165tk7T3YeOEQIOFcuyRsHivLOdA1yfUgVzEwXAxBIXM/edit?usp=sharing

**Comment by christianbltr** [comment]
Danke! :-)
