### ISSUE TITLE
Not seeing all preview teasers - random depending on character count

### ISSUE THREAD

**Issue by SadlerJohnson** [teaminmedias-pluswerk/ke_search#134]
On our website (http://eleven.ort.org) ke_search does not consistently display all teasers in the search results when using the option, “Show abstract if it contains search-word, otherwise show and excerpt from the content.” The teasers which are displayed depends on the value of “Number of characters used for the result preview text”.

As an example, searching for “Аматус Лузитанский” returns a total of 9 hits. Depending on the teaser character count, some teasers display and some do not and it is different for every character count.  Testing teaser character counts from 100 to 2000 gives this set of results showing the teasers out of 9 hits of the result set that get displayed:

100=	189 (Teasers are shown for consecutive results 1, 8 and 9)
200=	24
300=	149
400=	269
500=	47
600=	189
700=	12346
800=	236789
900=	589
1000=	1789
1100=	12789
1200=	189
1300=	1479
1400=	47
1500=	12456
1600=	127
1700=	139
1800=	19
1900=	1479
2000=	189

I couldn’t get more than 6 teasers to display with this example (for 800 chars). I think that teasers should be shown for all hits and be independent from teaser character count. Willing to do more testing/debugging.

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
