### ISSUE TITLE
Call to undefined method TYPO3\CMS\Core\Utility\GeneralUtility::inArray() 

### ISSUE THREAD

**Issue by yauhensk** [teaminmedias-pluswerk/ke_search#136]
It seems should be ArrayUtility::inArray

**Comment by dr-bock** [comment]
Can confirm the exception.

But ArrayUtility::inArray is deprecated.
-> https://docs.typo3.org/typo3cms/extensions/core/8.7/Changelog/8.6/Deprecation-79316-DeprecateArrayUtilityinArray.html

**Comment by lochmueller** [comment]
👍 Also confirm this issue...

**Comment by christianbltr** [comment]
fixed with https://github.com/teaminmedias-pluswerk/ke_search/pull/138

**Comment by raWINce** [comment]
Fix contains a bug:
https://github.com/teaminmedias-pluswerk/ke_search/issues/153
