### ISSUE TITLE
Tags for faceted search: "Unknown type: select"

### ISSUE THREAD

**Issue by mrvoss** [teaminmedias-pluswerk/ke_search#14]
In the current version 19e65202199380e72cd25cce15c9d1ea7eb228ac / 20151203, it is impossible to assign ke_search tags to pages. Instead of a select box with available tags on the categories tab, an error "Unknown type: select" is displayed.

Fix:

Add "'renderType' => 'selectSingleBox'," to the TCA definition in ext:ke_search/ext_tables.php:

```
 ext_tables.php | 1 +
 1 file changed, 1 insertion(+)

diff --git a/ext_tables.php b/ext_tables.php
index a8e3ae9..818d723 100644
--- a/ext_tables.php
+++ b/ext_tables.php
@@ -17,6 +17,7 @@ $tempColumns = array(
    'label' => 'LLL:EXT:ke_search/locallang_db.xml:pages.tx_kesearch_tags',
    'config' => array(
        'type' => 'select',
+       'renderType' => 'selectSingleBox',
        'size' => 10,
        'minitems' => 0,
        'maxitems' => 100,

```

See https://forge.typo3.org/issues/71622 , https://docs.typo3.org/typo3cms/TCAReference/Reference/Columns/Select/Index.html#rendertype for details.

**Comment by christianbltr** [comment]
Thanks. Has been fixed in dev-master.
