### ISSUE TITLE
Missing escaping for regex

### ISSUE THREAD

**Issue by liayn** [teaminmedias-pluswerk/ke_search#140]
> Core: Error handler (FE): PHP Warning: preg_replace(): Compilation failed: missing ) at offset 14 in /.../web/typo3conf/ext/ke_search/Classes/lib/class.tx_kesearch_lib_searchresult.php line 225

```
$word = str_replace('/', '\/', $word);
$word = htmlspecialchars($word);
$content = preg_replace('/(' . $word . ')/iu', $highlightedWord, $content);
```

The reason is a missing escaping of the search word for the regex with `preg_quote()`
The first line of the above code is then superfluous.

**Comment by christianbltr** [comment]
These lines have been changed in current master.

See https://github.com/teaminmedias-pluswerk/ke_search/blob/master/Classes/lib/class.tx_kesearch_lib_searchresult.php#L223

Could you please check if the Warning still exists?

**Comment by liayn** [comment]
@christianbltr IMO this is a very bad idea. Why do you "implement" the quoting yourself instead of using the emthod `preg_quote` directly?

`$word = preg_replace('/([?#^&*()$\\/])/', '\\\\$1', $word);`
vs
`$word = preg_quote($word);`

**Comment by christianbltr** [comment]
Thanks for your hint. That's indeed better.

**Comment by christianbltr** [comment]
connected to https://github.com/teaminmedias-pluswerk/ke_search/pull/119
