### ISSUE TITLE
Feature request: Enable/Disable indexing of headers

### ISSUE THREAD

**Issue by pixelbrackets** [teaminmedias-pluswerk/ke_search#144]
Feature request: Add a TypoScript settings to enable/disable indexing of headers in content elements.

Use case: Header fields ma be used for backend only or contain text which should not be indexed.

Enviroment:
ke_search Version 2.5.0
ke_search/Classes/indexer/types/class.tx_kesearch_indexer_types_page.php Line 436

**Comment by christianbltr** [comment]
If you set headers to "hidden" they won't be indexed.
Other cases are quite special in my opinion and should therefore be handled by custom hooks or indexers.
Therefore I'm closing this issue.
