### ISSUE TITLE
TYPO3 8.7 indexing of other languages (page indexer) than default will fail

### ISSUE THREAD

**Issue by cosmox** [teaminmedias-pluswerk/ke_search#148]
We try to index the content on a multilanguage site but ke_search will never index other content as the default content, so i take a look inside the Page indexer, i guess i found two bugs inside the methode for getting the content for the other languages, original method:

`    public function addLocalizedPagesToCache($pageRow)
    {
        // create entry in cachedPageRecods for default language
        $this->cachedPageRecords[0][$pageRow['uid']] = $pageRow;

        // create entry in cachedPageRecods for additional languages, skip default language 0
        foreach ($this->sysLanguages as $sysLang) {
            if ($sysLang[1] > 0) {
                list($pageOverlay) = \TYPO3\CMS\Backend\Utility\BackendUtility::getRecordsByField(
                    'pages_language_overlay',
                    'pid',
                    $pageRow['uid'],
                    'AND sys_language_uid=' . intval($sysLang[1])
                );
                if ($pageOverlay) {
                    $this->cachedPageRecords[$sysLang[1]][$pageRow['uid']] = GeneralUtility::array_merge(
                        $pageRow,
                        $pageOverlay
                    );
                }
            }
        }
    }`

Using ob $sysLang[1] to getting the uid for this language will maybe fail, because you dont know, is this really the right position for the uid inside this array, suggestion here use: $sysLang['uid']

Using GeneralUtility::array_merge is a bad idea, because this method is deprecated and removed, see: https://forge.typo3.org/issues/64596 using the nativ php method will fix this. I made these changes inside the class.tx_kesearch_indexer_types_page.php class file, and now i see that other than the default language are indexed:

`    public function addLocalizedPagesToCache($pageRow)
    {
        // create entry in cachedPageRecods for default language
        $this->cachedPageRecords[0][$pageRow['uid']] = $pageRow;

        // create entry in cachedPageRecods for additional languages, skip default language 0
	foreach ($this->sysLanguages as $sysLang) {
		if ($sysLang['uid'] > 0) {
                list($pageOverlay) = \TYPO3\CMS\Backend\Utility\BackendUtility::getRecordsByField(
                    'pages_language_overlay',
                    'pid',
                    $pageRow['uid'],
                    'AND sys_language_uid=' . intval($sysLang['uid'])
                );
                if ($pageOverlay) {
                    $this->cachedPageRecords[$sysLang['uid']][$pageRow['uid']] = array_merge(
                        $pageRow,
                        $pageOverlay
                    );
                }
            }
        }
    }`

**Comment by cosmox** [comment]
mmm this is the same issue like #135 maybe someone can merge these issues

**Comment by christianbltr** [comment]
fixed with https://github.com/teaminmedias-pluswerk/ke_search/pull/146
