### ISSUE TITLE
Call to a member function modifyFilters() on null  and Call to a member function modifyPagesIndexEntry() on null

### ISSUE THREAD

**Issue by vmans** [teaminmedias-pluswerk/ke_search#152]
What can be a reason for this to happen? After upgrading from 7.6 to 8.7. Using version 2.5.0.

---
error 1) Call to a member function modifyFilters() on null 

Error thrown in file
/home/sites/clients/client12/web49/web/typo3conf/ext/ke_search/Classes/lib/class.tx_kesearch_filters.php in line 74.

error 2) Call to a member function modifyPagesIndexEntry() on null

Error thrown in file
/home/sites/clients/client12/web49/web/typo3conf/ext/ke_search/Classes/indexer/types/class.tx_kesearch_indexer_types_page.php in line 492.

It looks like there is no content fetched so it makes sense that error 1 occurs. But why?

```
18 tx_kesearch_indexer_types_page::getPageContent(7779)

/home/sites/clients/../typo3conf/ext/ke_search/Classes/indexer/types/class.tx_kesearch_indexer_types_page.php:

00215:         foreach ($indexPids as $uid) {
00216:             if ($uid) {

00217:                 $this->getPageContent($uid);

00218:             }
00219:         }
```

Thanks,
Vincent

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
