### ISSUE TITLE
in_array used incorrectly

### ISSUE THREAD

**Issue by raWINce** [teaminmedias-pluswerk/ke_search#153]
[Here](https://github.com/teaminmedias-pluswerk/ke_search/blob/master/Classes/lib/class.tx_kesearch_lib_sorting.php#L196) it should be

```
$isInArray = in_array($direction, $allowedDirections, true);
```

and **not**

```
$isInArray = in_array($allowedDirections, $direction, true);
```

Please consider fixing.  
Many Thanks!

**Comment by christianbltr** [comment]
Thanks. Has been fixed in current master.
