### ISSUE TITLE
Typo when reading conf for highlightedWord_stdWrap

### ISSUE THREAD

**Issue by raWINce** [teaminmedias-pluswerk/ke_search#154]
[In this file](https://github.com/teaminmedias-pluswerk/ke_search/blob/master/Classes/lib/class.tx_kesearch_lib_searchresult.php#L218) please replace  `$this->conf['highlightedWord_stdWrap.']` by `$this->conf['highlightedWord_stdWrap']`

Many Thanks!

**Comment by kszymukowicz** [comment]
Confirmed.

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis und mit Dienstag, 02.01.2018 abwesend. 

Ihr E-Mail wird nicht weitergeleitet und erst am Mittwoch, 03.01.2018 gelesen.

In dringenden Fällen kontaktieren Sie Herr Bruno Buess (buess@netconsult.ch, Tel.  031 352 00 88).

Besten Dank.


Freundliche Grüsse
Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch
