### ISSUE TITLE
Wrong 2.5.0 gets installed

### ISSUE THREAD

**Issue by vmans** [teaminmedias-pluswerk/ke_search#156]
[ke_search-2.5.0-dev-master.pdf](https://github.com/teaminmedias-pluswerk/ke_search/files/1310470/ke_search-2.5.0-dev-master.pdf)

See the attachment. From clean situation, and using composer, the old 2.5.0 from 31-05-2017 gets installed with for example an inArray issue.

What do I miss here?

**Comment by christianbltr** [comment]
The version 2.5.0 indeed has been released on 31. 5. 2017.
All the commits after that date are only in master (without version number) and have not been released.
You can download master using this link:
https://github.com/teaminmedias-pluswerk/ke_search/archive/master.zip

Does this help you?

**Comment by vmans** [comment]
Hi,

No, it doesn't since I use composer mode... It is recommended to use composer so I'm following that. I know how to use the zips and so. (These days it's made more complicated than ever before.)

But what can you do? For instance, release a dev or preliminary version?

**Comment by christianbltr** [comment]
You can use dev-master in composer or you have to wait for the next release.

**Comment by vmans** [comment]
That's the whole point: I ask for dev-master and I get this v.2.5.0. Tried it again, and al the warnings and errors of the previous 2.5.0 are back. Perhaps something goes wrong here on my side.

Anyway: the stable AND the dev-master of ke_search are not fit for 8.7 so you should delete this constraint from ext_emconf.php because it keeps people busy for hours and days.

**Comment by christianbltr** [comment]
Could you test again with the current 2.6.0?

**Comment by vmans** [comment]
Done, it works. Thanks!
