### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by ute-arbeit** [teaminmedias-pluswerk/ke_search#163]
In Typo3 8.7.8 I get the following warning when the ke_search indexer task is run by the cron job:

Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /htdocs/typo3/typo3conf/ext/ke_search/Classes/lib/class.tx_kesearch_lib.php line 315

The error does not arise when I'm running the task manually. As in this case the task is run by an ad-hoc admin user it might have to do with the rights granted to the _cli_scheduler user? _cli_scheduler is allowed to access the file storage in fileadmin but nothing else. Should I provide him with additional access rights?

**Comment by christianbltr** [comment]
At that point the FlexForm Configuration is copied the general configuration of the plugin. This is'n a problem with access rights. Will have take a closer look.

**Comment by ute-arbeit** [comment]
I'm very sorry, it's not during the indexing it's during the search. I did a search immediately after each run of the scheduler and misinterpreted the log files.
Actually the warning is thrown for every search, searching from the search box as well as from the result list page.
I think this is only the case since the update to 8.7.8.

**Comment by christianbltr** [comment]
I'm sorry, I could not reproduce this on a 8.7.8 test system. Do you still have the issue? Can you explain further how to reproduce it?

**Comment by ute-arbeit** [comment]
The problem does still exist. Today I've tested it on a 8.7.9 system and the error is the same.
Every search throws two identical errors (severity is "Warning"), no matter if I search from the search box in the header or the search result page:
"Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /htdocs/typo3/typo3conf/ext/ke_search/Classes/lib/class.tx_kesearch_lib.php line 315"
![clipboard01](https://user-images.githubusercontent.com/18173051/34192458-733db342-e54e-11e7-9e49-c3b14f7668c0.png)

The search results seam to be totally correct and are not affected by the error as far as I can see.
I use a search box/form without any additional option fields.
Maybe the problem is connected to language variables as line 315 reads:
<code>foreach ($lang as $key => $value) {</code>
The website is for one language only and so I do not use a linkVar for language, in fact no linkVars at all (<code>linkVars =</code> in TypoScript setup).
Could this be the reason for the error?

**Comment by ute-arbeit** [comment]
I found the reason for the error message:

The flexform data in field `pi_flexform` in table `tt_content` for the page element with the search plugin contained amongst other data an empty `language` element
```xml
<sheet index="main">`
    <language index="lDEF"></language>`
</sheet>
```
which resulted in an empty string insted of an array as argument for `foreach` in line 315 of class.tx_kesearch_lib.php (the last line of the code snippet):
```php
$piFlexForm = $this->cObj->data['pi_flexform'];
if (is_array($piFlexForm['data'])) {
    foreach ($piFlexForm['data'] as $sheetKey => $sheet) {
        foreach ($sheet as $lang) {
            foreach ($lang as $key => $value) {
                ...
```
I don't know how this empty element was added to the flexform data. To prevent similar errors one could place a condition before the `foreach` loop
```php
        if (is_array($lang)) {
            foreach ($lang as $key => $value) {
                ...
```
or a `try...catch`
```php
        try {
            foreach ($lang as $key => $value) {
                ...
```

**Comment by christianbltr** [comment]
Thank you for clearing this!

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
