### ISSUE TITLE
Non-leading search strings should not be marked in the search results in standard edition of ke_search

### ISSUE THREAD

**Issue by ute-arbeit** [teaminmedias-pluswerk/ke_search#164]
Except for the premium version substrings are only found if they are at the first position in the word (e.g. _childhood_ -> _child_ is found, _hood_ is not found).
Therefore non-leading search strings (like _hood_ in _childhood_) should not be underlined in the search results in the standard version of the extension. These words containing this non-leading search string are not results of the search but only accidentially contained in the indexed document or page. The correct search result(s) is/are elsewhere in the  document/page.

**Comment by ute-arbeit** [comment]
By examining the source code I found that correct marking of the search results is achieved with a slightly modified regular expression in the `highlightArrayOfWordsInContent` method of ke_search/Classes/lib/class.tx_kesearch_lib_searchresult.php.

So in the standard version of the plugin where only leading substrings are found by the indexer the correct expression for strings to mark is 
`                $content = preg_replace('/\b(' . $word . ')/iu', $highlightedWord, $content);
`
instead of 
`                $content = preg_replace('/(' . $word . ')/iu', $highlightedWord, $content);
`
to find only strings starting at word boundaries.

**Comment by christianbltr** [comment]
Thanks. Fixed in current master.

Should now work as expected.

![auswahl_016](https://user-images.githubusercontent.com/11410553/34117849-2f50ff0e-e41d-11e7-9a13-013e548e16f6.png)
