### ISSUE TITLE
REPLACE GeneralUtility::getUserObj by GeneralUtility::makeInstance

### ISSUE THREAD

**Issue by vmans** [teaminmedias-pluswerk/ke_search#167]
In class.tx_kesearch_filters.php line 75... and other places?

https://docs.typo3.org/typo3cms/extensions/core/Changelog/master/Deprecation-80993-GeneralUtilitygetUserObj.html

**Comment by drmmch** [comment]
Shouldn't this be moved to https://github.com/teaminmedias-pluswerk/ke_search/milestone/2 since it breaks bc?

**Comment by christianbltr** [comment]
This has already been fixed (in version 3.0.0).
