### ISSUE TITLE
Documentation of previewImage sizing

### ISSUE THREAD

**Issue by kimchristiansen** [teaminmedias-pluswerk/ke_search#169]
I had to debug the sourcecode on how to resize the previewImage.
I found out, that i can change the maxW and maxH in the typoscript like this:

```
plugin.tx_kesearch_pi2.previewImage.file.maxW = 640
plugin.tx_kesearch_pi2.previewImage.file.maxH = 480
```

It would be great to find things like this in the documentation.

**Comment by christianbltr** [comment]
In current master / version 3 the image sizes are currently hardcoded in the fluid template, so you will have to adjust that template. That has now been documented in https://github.com/teaminmedias-pluswerk/ke_search/blob/master/Documentation/Templating/Images.rst.
