### ISSUE TITLE
sorting: error when sorting is enabled

### ISSUE THREAD

**Issue by ulrike-cosmoblonde** [teaminmedias-pluswerk/ke_search#170]
Regarding Version 2.5.0

When enabling sorting for ke_search, I get a php error msg in the frontend:
PHP Warning: in_array() expects parameter 2 to be array, string given in ke_search\Classes\lib\class.tx_kesearch_lib_sorting.php line 196

The code in file class.tx_kesearch_lib_sorting.php line 196 is:
$isInArray = in_array($allowedDirections, $direction, true);

By swapping the 2 parameters, the problem should be solved as the required parameters should be in the following order: in_array ($needle, array $haystack, $strict = null)

Regards,
Ulrike

**Comment by ulrike-cosmoblonde** [comment]
Same problem in file ke_search\Classes\lib\class.tx_kesearch_filters.php line 119.
The parameters need to be swapped:
 $isInArray = in_array($option['tag'], $this->pObj->piVars['filter'][$filter['uid']]);

**Comment by christianbltr** [comment]
This has been fixed in 
https://github.com/teaminmedias-pluswerk/ke_search/commit/ead45e31bc1ca688d868a6d7057a659f1a4a4763

Please use the current version of ke_search.
