### ISSUE TITLE
Splitting the Indexing Process and have a Scheduler for each IndexerConfiguration

### ISSUE THREAD

**Issue by cabi** [teaminmedias-pluswerk/ke_search#171]
Hi,

I have the problem of very large files with a huge amount of product-data. This product-data change very seldom (the indexing process take some hours)  and I don't want to reindex them when some news changed.

So I think it is nice to have different frequencies in Indexing the data.

For example:
* index the pages once a day
* index the news every hour
* index a large pile of product-data once a month

This I solved by hooking and xclassing the Indexer and extending the `tx_kesearch_indexerconfig` table.

Each IndexerConfiguration has 3 new fields
- frequency (CRON style like in the scheduler)
- cli_only (Checkbox to run this configuration only in cli-mode)
- last_run (when this configuration run last)

Then in the `\tx_kesearch_indexer::startIndexing` method I check in the loop over the active configurations the frequency and the cli_run. If both values met the criteria the indexer start to run - if not the loop will be continued.

Here I ran in the cleanup-process in the problem, that only the indexer-name as `type` is in the `tx_kesearch_index` table. The `uid` of the indexer-configuration may be here much faster (WHERE with type = (Number) is faster than string comparison) and I can run different configurations with the same type in different frequencies.

I have now a working version but as a really nice scheduling solution it need much more refactoring in the ke_search-classes.

This may a feature for later versions (maybe when converting the Extension into namespaces?)

Greetings,
Carsten

**Comment by christianbltr** [comment]
Hi Carsten, thanks, yes, that's great stuff and would be useful in many installations with bigger data volume. Definitely an interesting feature for future versions.

Why did you choose to add the "frequency" in the indexer configuration?
My approach would be to add a scheduler task for each frequency and make it possible to select in the scheduler task which indexer configurations should be executed. This way the whole logik of what is when executed is done by the scheduler.

I think it's a good idea to add the uid of the indexer configuration in the indexer table. This way the cleanup process can only cleanup the data which has just been indexed, not the whole index table.

A next step could be to add a button for each individual indexer configuration in the backend module and allow to execute individual indexer configurations ad hoc, eg. for news elements without having to wait for the complete indexer to complete.

**Comment by Mainbird** [comment]
Hi Christian,
is there any progress here or is the feature still planned?

**Comment by christianbltr** [comment]
We now have the "incremental indexing" feature in ke_search which kind of solves the same problem. It indexes only data which changed since the last indexing time. This results in a greatly reduced indexing time. See also https://docs.typo3.org/p/teaminmedias-pluswerk/ke_search/master/en-us/Indexing/Index.html

So currently there are no plans to split up the indexing process.
