### ISSUE TITLE
Setting the CLI-Mode for the Indexer 

### ISSUE THREAD

**Issue by cabi** [teaminmedias-pluswerk/ke_search#172]
Hi,

setting the CLI mode for the Indexer without real checkin for the CLI mode is not so good.

Example: typo3conf/ext/ke_search/Classes/Scheduler/class.tx_kesearch_indexertask.php
```
$indexer->startIndexing(true, $this->extConf, 'CLI');
```
Checking for the CLI-Enviroment like

```
if (php_sapi_name() == 'cli') {
$mode = 'CLI';
}
```
may prevent some problems if the cli-mode is not only used for displaying purpose.

Greetings,
Carsten

**Comment by christianbltr** [comment]
See https://github.com/tpwd/ke_search/issues/99
