### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by rowild** [teaminmedias-pluswerk/ke_search#174]
First of all: AWESOME!!! Works fantastic! Thanks SOOOO MUCH!!!!

I have some very minor questions and hope that this is the right place for it:

1. shouldn't the input field for the search word not be of type=search instead of text? (Functionality us equal, but browser rendering might be different and could include better accessibility features.) 

2. The "reset" button redirects to the search result page - which is confusing, when the result page is a separate page. All I expect is that the search field gets emptied. Or do I misunderstand something here?

3. Currently there are no fluid templates for pager (and other little things), which make consistent page styling cumbersome. Do you plan to integrate fluid fully? Would be great! If there woul dbe a chance to upvote for it, I'd do so right here and right now! :-)

Thanks again!

**Comment by christianbltr** [comment]
Thanks for your suggestions, they sound sensible to me. Fluid based pagination is already on the list (there's an issue for that: https://github.com/teaminmedias-pluswerk/ke_search/issues/81).

**Comment by rowild** [comment]
#81 looks good, but it seems the contributer is not really active (the files are from February). Any chance you could do the implementation by yourself?

**Comment by rowild** [comment]
Really waiting for fluid-based pagination. UP-VOTING!

**Comment by christianbltr** [comment]
Fluid-bases pagination is now included (in dev-master, will be in 2.7.0)
https://github.com/teaminmedias-pluswerk/ke_search/pull/183

**Comment by christianbltr** [comment]
1. Input field is now of type "search" (since version 3.6.0).

2. The reset button needs to reload the page in order to update the result list accordingly. So we cannot simply clear the input field here.

3. Fluid based pagination has been implemented (see comments before).
