### ISSUE TITLE
Support for Fallback-Fluid-Paths..

### ISSUE THREAD

**Issue by bernhardberger** [teaminmedias-pluswerk/ke_search#18]
Please add Support for Fallback-Fluid-Paths.. 

tx_kesearch_pi1 {
  templateRootPaths.100 = ...
//etc.
}

I may provide pull request that fixes that if time allows me to..

**Comment by christianbltr** [comment]
Great, go ahead!

See also
https://forge.typo3.org/issues/72804

**Comment by bernhardberger** [comment]
I've looked into this issue because I was having the same idea.. unfortunately this isn't that easy as ke_search uses a StandaloneView which doesn't actually support fallback templateRootPaths.. it's partially fixable for the partialRootPaths and layoutRootPaths, but for the templateRootPaths to work one would actually have to use a ActionController based view logic.

I may look into this again at another time..

**Comment by jensengelmann** [comment]
@christianbltr Any chance the pull request (https://github.com/teaminmedias-pluswerk/ke_search/pull/73) gets merged? There's no breaking change - everything still works fine.

**Comment by christianbltr** [comment]
This feature has been implemented in 
https://github.com/teaminmedias-pluswerk/ke_search/pull/96
