### ISSUE TITLE
Filter by Date

### ISSUE THREAD

**Issue by arirangz** [teaminmedias-pluswerk/ke_search#180]
Hi,

I would like to know if it's possible to add a filter Date such as on google:
Past hour
Past date
...
From XXX to XXX

Many thanks

**Comment by christianbltr** [comment]
That's not possible out-of-the-box.

**Comment by arirangz** [comment]
Thanks for your answer.

Could you please guide me a little on how I can achieve this?

Many thanks

**Comment by arirangz** [comment]
By the way, I am using v2.2.1 as I'm on typo 6.2

Thanks

**Comment by arirangz** [comment]
Is there a hook I can use to filter the date? Are you already storing the lastModified date on your index table?

Thanks

**Comment by arirangz** [comment]
Ok I could achieve this adding a hook on getQueryParts

**Comment by deroccha** [comment]
Hi @arirangz can you give me a hint how did you fixed this issue?

**Comment by arirangz** [comment]
hi @deroccha 

This was an old project so I don't remember well but here is the hook I used:
[https://pastebin.com/bwMBU44E
](https://pastebin.com/bwMBU44E
)
Hope this will help

**Comment by tangananica24** [comment]
> hi @deroccha
> 
> This was an old project so I don't remember well but here is the hook I used: [https://pastebin.com/bwMBU44E ](https://pastebin.com/bwMBU44E) Hope this will help



> Hi @arirangz can you give me a hint how did you fixed this issue?

Hey! Could you implement it? How did you do it? I'm really confused 😕
