### ISSUE TITLE
Filter on Category

### ISSUE THREAD

**Issue by arirangz** [teaminmedias-pluswerk/ke_search#181]
Hi,

Faceting is using it's own tag system.

Is it possible to create a filter based on page categories?

Thanks

**Comment by christianbltr** [comment]
You mean system categories? A filter is not created automatically for system categories. But ke_search automatically adds tags for system categories like this: syscat123 where 123 is the uid of the system cateogory. You can then create filter options for this tag: Create a filter option, name like want to and set "syscat123" as tag.

Remember to add a filter option each time you add a new system category.

**Comment by arirangz** [comment]
Do you mean that if I name the tag abc123 with 123 as the ID of a system category, it will filter on pages that have this category set?
Is this in the documentation?
Thanks for your help!

**Comment by arirangz** [comment]
So I created a filtrer with filter option xxx123 where 123 is the ID of the category, for xxx I put a random name.  But it doesn't work.
Is the xxx as to match with the system category name? If yes, you slugify the category name?

Where can I see the tag created automatically from categories?

Thanks!

**Comment by christianbltr** [comment]
Please do not use a random name, use "syscat" + category UID, eg. "syscat123" as tagname.

In order to see the tags which have been created automatically, switch to "Indexed content" in the backend module and select a page.

**Comment by arirangz** [comment]
Ok great it works.

Thanks a lot!
