### ISSUE TITLE
Filter on file type

### ISSUE THREAD

**Issue by arirangz** [teaminmedias-pluswerk/ke_search#182]
Hello,

Is it possible to add filter on the file type such as PDF or XLS, or DOC?

Thanks!

**Comment by christianbltr** [comment]
That's not possible out-of-the-box.

**Comment by arirangz** [comment]
Ok thanks. Could you please guide me a little on how I could achieve this?

**Comment by christianbltr** [comment]
You could hook into the page indexer or file indexer and add a tag to the created index record according to the file type.

If you're using the file indexer (not indexing files with the page indexer) you could create an indexer configuration for each file type and add use the function "add tag to all records from this indexer configuration". That would be a way without any additional coding.

**Comment by arirangz** [comment]
Indeed, that sounds great to do it with the file indexer.

Thanks a lot!
