### ISSUE TITLE
multi-byte safe string operations

### ISSUE THREAD

**Issue by FlorianX** [teaminmedias-pluswerk/ke_search#187]
buildTeaserContent in class.tx_kesearch_lib_searchresult performs no multi-byte safe string operations.
If the teaser contains UTF-8 Chars like "üäöşığ" the used string operations leads to � marks and miss cropping of the teaser.

Is there any reason why this was ignored during implementation?

**Comment by christianbltr** [comment]
This has been fixed with https://github.com/teaminmedias-pluswerk/ke_search/commit/20830f8e21f9dc67acd6b4f69df0b64d0236b7cf
