### ISSUE TITLE
Incorrect integer value in strict mode

### ISSUE THREAD

**Issue by Smove** [teaminmedias-pluswerk/ke_search#190]
**_This behaviour is appears only if sql strict mode is on(default on newer mysql/mariadb versions)._**
When indexing using the pages indexer, tx_kesearch_indexer->insertRecordIntoIndex throws an sql error on line 547 using the latest release from TER. 

> Incorrect integer value: '' for column 'orig_pid' at row 1

There should be a 0 instead of the empty value to fix this issue.

**Comment by infabo** [comment]
Can confirm this.

**Comment by christianbltr** [comment]
fixed with https://github.com/teaminmedias-pluswerk/ke_search/commit/6b455c34d3f7fc74936692923b813fb5b0ba331d

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Can this be reopened, please? Happens with latest TYPO3 and ke_search 3.7.2 with MariaDB 10.2.37-MariaDB in strict mode:

Mon, 17 May 2021 09:41:17 +0200 [ERROR] request="1da8ff4639e6d" component="TeaminmediasPluswerk.KeSearch.Indexer.IndexerRunner": An exception occurred while executing 'EXECUTE insertStmt USING @pid, @title, @type, @targetpid, @content, @tags, @params, @abstract, @language, @starttime, @endtime, @fe_group, @tstamp, @crdate, @sortdate, @orig_uid, @orig_pid, @directory, @hash;':

Incorrect integer value: '' for column `[db_name]`.`tx_kesearch_index`.`sortdate` at row 1
