### ISSUE TITLE
Search string with value in search form with " " (Apostroph) will get wrong results

### ISSUE THREAD

**Issue by angeloprevitali** [teaminmedias-pluswerk/ke_search#193]
If you search for example "mykeyword" with the word in the apostroph the variable {numberofresults} gets no results BUT a value of 1. If you search for the same word mykeyword (that can be really found in the content)  the search results will get the correct results of the page with the keyword and the variable {numberofresults} gets also a value of 1.

**Comment by christianbltr** [comment]
Which database are you using?

There's a bug in MySQL 5.7 and InnoDB, see https://bugs.mysql.com/bug.php?id=78485

Could you try setting the tx_kesearch_index to myISAM?

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis und mit Sonntag, 10.06.2018 abwesend. 

Ihr E-Mail wird nicht weitergeleitet und erst am Montag, 11.06.2018 gelesen.

In dringenden Fällen kontaktieren Sie Herr Bruno Buess (buess@netconsult.ch, Tel. 031 352 00 88).

Besten Dank.


Freundliche Grüsse
Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch

**Comment by angeloprevitali** [comment]
We are using mySQL DB version 5.5.

**Comment by teaminmedias-pluswerk** [comment]
has been fixed now, see #214
