### ISSUE TITLE
Error with MariaDB 10.2

### ISSUE THREAD

**Issue by Lumrenion** [teaminmedias-pluswerk/ke_search#195]
Hi,
I extended ke_search and implemented an ajax pagination (directly calling pi2). As I call pi2 directly without calling pi1 before, in Class `tx_kesearch_lib_div` pObj is pi2 and method `getStartingPoint` executes query
```
$res = $GLOBALS['TYPO3_DB']->exec_SELECTquery(
    'pages, recursive',
    'tt_content',
    'uid = ' . $uid
);
```

In MariaDB 10.2, `recursive` is a key word, so it must be escaped in query.

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
