### ISSUE TITLE
Performance Problem (resulting in PHP Timeout) if searchterm not found in index

### ISSUE THREAD

**Issue by mrcli** [teaminmedias-pluswerk/ke_search#199]
Hi,
if a user searches for a term not existing in index the result is a php timeout. The plain sql statement fired directly on the mysql db delivers a result in 1 to 1.5s.

ke_search: 2.4.0
TYPO3: 7.6.23
MySQL: Galera Cluster (Galera related/ innoDB commits ccb040d64d2c5e0308e41516c2e29fdc93a6ca04 and a0092484e445000d521f0d4d70debaec1d07d648 cherry picked in forked repo)
tx_kesearch_index entries: ~5000

Any idea, why it is so slow if nothing is found by a searchterm? Are there any heavy known functions I can observe to find the problem? Any hints?

Best regards

**Comment by mrcli** [comment]
note: percent of score is disabled

**Comment by christianbltr** [comment]
This should be fixed with https://github.com/tpwd/ke_search/commit/bff3330ec962eae8b5458324be9e0112739ecd1d

If you still experience problems, please open an issue in https://github.com/tpwd/ke_search/issues
