### ISSUE TITLE
Same file appears multiple times in search result

### ISSUE THREAD

**Issue by galum** [teaminmedias-pluswerk/ke_search#202]
**Situation**: Page indexer stores it's index data in a data sub-folder. The page indexer indexes PDF files linked in pages. The same PDF file is linked in multiple pages. 

**Malfunction**: The same file appears in search results multiple times. When checking the database entries, the same file with the same hash and same other parameters appears multiple times.

**Possible cause**: I did some logging, and the problem is most probably a buggy int cast in function _checkIfFileWasIndexed_ in file _ke_search/Classes/indexer/class.tx_kesearch_indexer.php_. The $pid argument seems to be a quoted string (example: '528') and thus the int cast fails in the select statement:
`'SELECT * FROM tx_kesearch_index WHERE ' . 'type = ' . $type . ' AND hash = ' . $hash . ' AND pid = ' . (int) $pid . ' LIMIT 1'`
Because of the quotes, the cast always results in 0, and thus the _checkIfFileWasIndexed_ function always returns false.

**Possible fix**: Just remove (int) cast, or remove quotes before casting

**Comment by Mathesus** [comment]
Had the same problem at a project.
The possible fix helped, but this should be fixed for the next update.

**Comment by christianbltr** [comment]
There's a patch for this issue:
https://github.com/teaminmedias-pluswerk/ke_search/pull/235/commits/9743a490ebd5d6a7a140dd99aa307abac945e408

**Comment by christianbltr** [comment]
Fixed in Master, will be in version 2.8.1

**Comment by galum** [comment]
Thank you. Updating to version 2.8.1 solved the problem.
