### ISSUE TITLE
missing link-generation for rendering-type LIST [ checkFilterCondition = none ]

### ISSUE THREAD

**Issue by xerc** [teaminmedias-pluswerk/ke_search#207]
https://github.com/teaminmedias-pluswerk/ke_search/blob/206dd66448dcd856cb044c5ca81ec5963849fcab/Classes/lib/class.tx_kesearch_lib.php#L537-L545
https://github.com/teaminmedias-pluswerk/ke_search/blob/206dd66448dcd856cb044c5ca81ec5963849fcab/Classes/lib/class.tx_kesearch_lib.php#L581-L592

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
