### ISSUE TITLE
Template content of pagination / pagebrowser widget not rendered

### ISSUE THREAD

**Issue by typecat** [teaminmedias-pluswerk/ke_search#208]
I've tryed to use the pagination widget template promoted in [recent feature](https://github.com/teaminmedias-pluswerk/ke_search/pull/183/commits/66c3a1e7c1744569d66e0787fb45574e4ea6a3ab) but just can't get it rendered. My other overrides of the templates work fine, so this is not the problem, besides, the `{pagination -> f:debug()}` statement in the overridden widget template is displayed in frontend, only not the following HTML (even plain text).

In my opinion there is something missing in the fluid template (e.g. Partials/ResultRows.html) that tells the widget where it should be rendered.
The [original feature request](https://github.com/teaminmedias-pluswerk/ke_search/issues/22) provided an own view helper which code was transferred into class.tx_kesearch_lib.php

So my basic question is: How exactly to use this template? An example code would be nice.

Using
TYPO3 7.6.23
EXT:ke_sreach 2.7.0

**Comment by typecat** [comment]
@christianbltr maybe you could post your example code of your patch test.
Or @TildBJ maybe could enlighten me/us as the author of this commit ;)

**Comment by teaminmedias-pluswerk** [comment]
Just tested it:

Add the template path like this:

plugin.tx_kesearch_pi1 {
	templateRootPaths.10 = fileadmin/ke_search/Resources/Private/Templates/
	partialRootPaths.10 = fileadmin/ke_search/Resources/Private/Partials/
	layoutRootPaths.10 = fileadmin/ke_search/Resources/Private/Layouts/
}
plugin.tx_kesearch_pi2 {
	templateRootPaths.10 = fileadmin/ke_search/Resources/Private/Templates/
	partialRootPaths.10 = fileadmin/ke_search/Resources/Private/Partials/
	layoutRootPaths.10 = fileadmin/ke_search/Resources/Private/Layouts/
}

And place your widget template into 
fileadmin/ke_search/Resources/Private/Templates/Widget/Pagination.html

**Comment by typecat** [comment]
My TypoScript setup looks like this:
![grafik](https://user-images.githubusercontent.com/30155820/39565799-abf805e6-4eb9-11e8-8f67-cdc78dccc7f3.png)
And the widget template is stored in EXT:<myext>/Resources/Private/Templates/Widget/Pagination.html
So the path to the widget seems correct. As described above, all the other overridden templates are being rendered correctly and the debug statement from the overridden widget template is also displayed in front end.

My code looks like this:

Partials/ResultRows.html
`<div class="search-result">`
`  <div id="kesearch_results" class="result">`
`    <ol>`
`      <f:for each="{resultrows}" as="resultrow">`
`        <f:render partial="ResultRow" arguments="{conf: conf, resultrow: resultrow}"/>`
`      </f:for>`
`    </ol>`
`  </div>`
`</div>`

I removed some wraps and the call of Partials/PageBrowser.html, because I want to use the widget template instead. The code of the widget template I haven't changed at all (except of inserting the debug statement at the top.

What I don't understand is:
a) why the debug statement is rendered, but not the HTML content
b) how to tell in the template WHERE the pagination widget should be rendered

**Comment by christianbltr** [comment]
I think that's the point: You removed the call of Partials/PageBrowser.html. That's where the Pagebrowser is rendered.

**Comment by typecat** [comment]
Now I get it! The widget template is rendered within Partials/PageBrowser.html. That's what you meant by "backwards compatibility". I thought the widget template is a replacement. That's why I removed the call of Partials/PageBrowser.html. I've overseen `'pages_list' => $view->render(),` in the marker array for the partial because I was concentrated on the widget.
**Please note this in the documentation.** This change totally messed up my old override of Partials/PageBrowser.html and that caused this whole confusion. I hope the more flexible way will now last for some versions. ;)
