### ISSUE TITLE
Feature Idea: combine with crawler

### ISSUE THREAD

**Issue by ursbraem** [teaminmedias-pluswerk/ke_search#210]
This is something that's in my head for a while: why not combine a ke_search with a crawler?

I imagine the following:

- A "classic" crawler crawls the site, like (or in fact) indexed_search, dropping indexed content into a table
- A ke_search indexer indexes said index 😃
- We could add some custom metadata on pages to pass along structured information (like content type), which would have to be interpreted by the indexer
- Now we would get a full, rendered content index for any kind of page content, including dce or mask elements, that can be used for all purposes, can be structured by metadata - and combined with specialised ke_search indexers

I've been having the following issues with the idea

- Nobody I talked to about this has found this an interesting idea, not even developers I've asked for paid work 😂
- Something seems fishy to me about indexed_search and even more, ext:crawler, which simply crashed our server at the first run...

what do you, as ke_search masterminds, think about that idea? should I invest more energy into that?

**Comment by christianbltr** [comment]
This might be a useful feature in specific contexts, but in our use cases we did not have a need for a "page crawler indexer".

Although I find it an interesting idea to build an indexer which indexes the indexed_search table and combine it with custom built indexers for specific use cases. 

As said, I guess it's a quite rare use case.

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
