### ISSUE TITLE
tt_news-categories not selectable in Indexer Configuration

### ISSUE THREAD

**Issue by sztop** [teaminmedias-pluswerk/ke_search#215]
When creating an indexer to search inside of tt_news-entries it is not possible to choose single news-categories after having chosen „Nur die folgenden Kategorien:“ in the form field „News der folgenden Kategorien indexieren:“. The form field „Kategorien“ remains greyed out, even if the configuration is saved in between.
My setup:
TYPO3 8.7.10
tt_news 8.7.0
ke_search 2.6.3

Best wishes
Andreas

**Comment by christianbltr** [comment]
Obsolete, since the tt_news indexer has been removed, see #248

**Comment by xerc** [comment]
https://github.com/rupertgermann/tt_news#compatibility .. may include it again?
