### ISSUE TITLE
pagination not working

### ISSUE THREAD

**Issue by anujaunds** [teaminmedias-pluswerk/ke_search#217]
When Click on pagination number the show this error.
Page Not Found
Reason: Request parameters could not be validated (&cHash comparison failed)

Also title didn't get url when we search in from.

**Comment by christianbltr** [comment]
Sorry, I cannot confirm this issue.
Which TYPO3 version are you using?

**Comment by anujaunds** [comment]
I am using 8.7.10

**Comment by christianbltr** [comment]
are you using ke_search master branch?

**Comment by anujaunds** [comment]
i just installed ke_search through composer

**Comment by anujaunds** [comment]
that is the pagination url:
?no_cache=1&tx_kesearch_pi1%5Bsword%5D=engineering&tx_kesearch_pi1%5Bpage%5D=2&tx_kesearch_pi1%5BresetFilters%5D=0&tx_kesearch_pi1%5BsortByField%5D=&tx_kesearch_pi1%5BsortByDir%5D=asc&cHash=a0e63e14c1ae480a0c8cb4ed99d25f11

**Comment by typecat** [comment]
I don't quite understand, what the actual problem is, but I've just updated to the latest version and my page browser broke also. This one helped me again and maybe helps you too:
https://github.com/teaminmedias-pluswerk/ke_search/issues/208#issuecomment-386271001

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
