### ISSUE TITLE
news link not get properly with title

### ISSUE THREAD

**Issue by anujaunds** [teaminmedias-pluswerk/ke_search#219]
Hi,

When i search something then it's get the pages title and link properly but it's get only news title not url. Could you let me how to resolve this problem. It's very urgent

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
