### ISSUE TITLE
Start Indexer error

### ISSUE THREAD

**Issue by plojewski** [teaminmedias-pluswerk/ke_search#223]
Hi there, when I try to start indexer I get an error:

> Oops, an error occurred!
> An exception occurred while executing 'SELECT `uid` FROM `pages` WHERE (`pid` = ?) AND (1=1) AND (`pages`.`deleted` = 0)' with params [108]: MySQL server has gone away

It runs Typo3 8.7.18, MySQL 5.5.5, PHP 7.0.31, ke_search 2.8.0.

Could you help please?

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
