### ISSUE TITLE
Empty segment in result URL

### ISSUE THREAD

**Issue by gvv1401** [teaminmedias-pluswerk/ke_search#224]
Hi,
any idea why result URL (to News details) has empty segment?
For example, http://typo3.siteid.webspaceconfig.de/details//organisation/ 
Expected: http://typo3.siteid.webspaceconfig.de/details/organisation/
Site is no multilanguage. News does not use categories.
Search xonfiguration:
![image](https://user-images.githubusercontent.com/10170885/44413801-ee716b80-a574-11e8-9460-2d9f5284827a.png)
![image](https://user-images.githubusercontent.com/10170885/44413912-27114500-a575-11e8-950f-713737c4ac9a.png)

TYPO3 - v.8.7.18
ke_search - v.2.8

**Comment by gvv1401** [comment]
I added var_dumps into class.tx_kesearch_lib_searchresult.php:
    public function getResultUrl($linked = false)
    {
        $linkText = $this->cObj->typoLink_URL($this->getResultLinkConfiguration());
		\TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump($this->getResultLinkConfiguration(), 'getResultLinkConfiguration');
        $linkText = htmlspecialchars($linkText);
		\TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump($linkText, '$linkText');
        if ($linked) {
            return $this->cObj->typoLink($linkText, $this->getResultLinkConfiguration());
        }
        return $linkText;
    }
and I see 
![image](https://user-images.githubusercontent.com/10170885/44459794-8aea4b00-a613-11e8-936d-8ccdbb6dab26.png)

I can't see any criminal in input params but output URL is wrong.

**Comment by martingebhardt** [comment]
Do you have found a solution?

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
