### ISSUE TITLE
@-symbol in 'sword' leads to exception

### ISSUE THREAD

**Issue by infabo** [teaminmedias-pluswerk/ke_search#226]
If you have a @-symbol in the search-word, it throws an PHP exception.

Example searches: "max@muster.de"

**Comment by christianbltr** [comment]
Hmm, never realized that. Thanks for pointing that out.

The @ character ist not supported by MySQL fulltext search when using InnoDB, as explained in the docs: "InnoDB full-text search does not support the use of the @ symbol in boolean full-text searches. The @ symbol is reserved for use by the @distance proximity search operator."
https://dev.mysql.com/doc/refman/8.0/en/fulltext-boolean.html

**Comment by infabo** [comment]
`(`
`)`
`/` (only when using GET as form-method)

**Comment by lorddoumer** [comment]
I have the same problem. 
@infabo is there a option to switch from get to post method for the ke_search plugin? don't see it anywhere

**Comment by teaminmedias-pluswerk** [comment]
This has been fixed with #214 since the new default storage engine for the index table has been switched back to MyISAM.
