### ISSUE TITLE
Resources currently in non standard path

### ISSUE THREAD

**Issue by garbast** [teaminmedias-pluswerk/ke_search#227]
Currently there are resources in old pathes like /typo3conf/ext/ke_search/res/img/table_icons/icon_tx_kesearch_indexerconfig.gif

This conflicts with the usage of helhum/typo3-secure-web which only exposes Resources/Public folders to public doc root.

Could you please move all css and image files to EXT:ke_search/Resources/Public/ ?

**Comment by teaminmedias-pluswerk** [comment]
Fixed in current branch compat9, will be in version 3 of ke_search.

**Comment by mikestreety** [comment]
Hey, thanks for a great plugin, sorry to dreg this issue back up, but this CSS file still references `typo3conf`.

https://github.com/teaminmedias-pluswerk/ke_search/blob/master/Resources/Private/Layouts/Backend/Default.html#L1

In my local install, I have changed it to `EXT:`  and works fine. Not fully tested!

(still using non-composer, plugins in `typo3/ext` method of loading - yes I know I need to update 😉 )

**Comment by christianbltr** [comment]
Thanks, this has been fixed in current master and will be in the next version.
