### ISSUE TITLE
Remove cli script and implement command controller 

### ISSUE THREAD

**Issue by teaminmedias-pluswerk** [teaminmedias-pluswerk/ke_search#229]
The use of CommandLineController has been deprecated.

https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.6/Deprecation-79265-CommandLineControllerAndCleanerCommand.html

The cli script located under cli/class.cli_kesearch.php should be transferred to a command controller or symfony command. 

https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/BackendModules/CliScripts/Index.html

**Comment by kiefer79** [comment]
The cli script was removed and replaced by a command controller: 

`bin/typo3 ke_search:indexbin/typo3 ke_search:index`

![kiefer_55](https://user-images.githubusercontent.com/3509209/50596336-38177e80-0ea4-11e9-9fef-a3c0354038d2.png)

In addition two more command controllers for clearing the whole index and removing the indexer lock were implemented: 

`bin/typo3 ke_search:clearindex`

![kiefer_59](https://user-images.githubusercontent.com/3509209/50596402-7f9e0a80-0ea4-11e9-9d17-7f9c4ecd53a0.png)

`bin/typo3 ke_search:removelock`

![kiefer_60](https://user-images.githubusercontent.com/3509209/50596495-cbe94a80-0ea4-11e9-89de-3da4c1aa5aed.png)
