### ISSUE TITLE
Migrate database queries to Doctrine commands

### ISSUE THREAD

**Issue by teaminmedias-pluswerk** [teaminmedias-pluswerk/ke_search#230]
The old school $GLOBALS['TYPO3_DB'] database commands should be migrated to Doctrine commands.

https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Database/Migration/Index.html

**Comment by christianbltr** [comment]
Most of the dabase queries have been migrated.

In some of the indexer classes the migration is not finished: tt_news, tt_content, TemplaVoila, tt_address, cal and a21glossary.

I will open new issues - either for migrating the database calls or for removing the indexer at all.

@kiefer79
