### ISSUE TITLE
Adopt new page translation handling of TYPO3 v9

### ISSUE THREAD

**Issue by teaminmedias-pluswerk** [teaminmedias-pluswerk/ke_search#233]
TYPO3 v9 comes with a new page translation handling. This should be reflected in ke_search.

Since the new handling can be enabled or disabled via a feature toggle, both ways should work in ke_search.

https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Breaking-82445-PagesAndPageTranslations.html

**Comment by kiefer79** [comment]
The handling of the "unifiedPageTranslationHandling" feature was added to the page indexer in commit 2c09ae2ede855fde2415ce600a7439513ae43f4a

No further query to table "pages_language_overlay" was found.
