### ISSUE TITLE
disabling css not possible

### ISSUE THREAD

**Issue by DavidBruchmann** [teaminmedias-pluswerk/ke_search#242]
the extension is always trying to load a css-file.
This is not always desired and disabling should be possible without any tricks like providing an empty file.

**Comment by kiefer79** [comment]
Loading a css file can be disabled by clearing the field `CSS File` in the plugin options. No css file should be loaded then.

**Comment by DavidBruchmann** [comment]
Sorry, that's not working.
Also by TypoScript I never had success.
Using branch compat9.

Correction:
**IT WORKS!
I HAD TO REMOVE THE CSS FOR BOTH PLUGINS (in TypoScript) TO GET RID OF EVERYTHING**

Thanks!
