### ISSUE TITLE
Call to a member function customIndexer() on null 

### ISSUE THREAD

**Issue by hasenbalg** [teaminmedias-pluswerk/ke_search#244]
Hi, I get the following exception in 2.7 and 2.8 using TYPO3 8.7.

>  Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function customIndexer() on null | Error thrown in file .../ext/ke_search/Classes/indexer/class.tx_kesearch_indexer.php in line 145. Requested URL: https://huhu.huhu/typo3/index.php?M=web_KeSearchBackendModule&moduleToken=--AnonymizedToken--&id=7&do=startindexer 

How can I determinate on which content it failed and why?

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
