### ISSUE TITLE
Problem by outputting URL in result list for CJK languages

### ISSUE THREAD

**Issue by lochmueller** [teaminmedias-pluswerk/ke_search#245]
Hey guys,

there are problems in the URL decoding of the URL in the result row.

Current state:
`
URL: /ja-jp/%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%94%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3/fascinaction/feel-style%E9%AD%85%E5%8A%9B%E7%9A%84%E3%81%AA%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3.jsp 
`

Expected result:
`
URL: /ja-jp/商品カタログ/引き戸および折れ戸扉システム.jsp 
`

Solution:
Patch: ke_search/Classes/lib/class.tx_kesearch_lib_searchresult.php
Function: getResultUrl

Code: `$linkText = htmlspecialchars($linkText);` should be `$linkText = htmlspecialchars(urldecode($linkText));`

Regards,
Tim

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
