### ISSUE TITLE
Migrate cal indexer

### ISSUE THREAD

**Issue by christianbltr** [teaminmedias-pluswerk/ke_search#251]
As soon as there's a version of cal for TYPO3 9 LTS the indexer should be migrated to doctrine calls. Currently there's no way to test it properly. In case there won't be a version of cal for TYPO3 9, the cal indexer should be removed.

**Comment by peerlight** [comment]
there's a version of cal for TYPO3 9 LTS for some month now:
https://gitlab.com/janhelke/cal/
