### ISSUE TITLE
Migrate a21glossary indexer

### ISSUE THREAD

**Issue by christianbltr** [teaminmedias-pluswerk/ke_search#252]
As soon as there's a version of a21glossary for TYPO3 9 LTS the indexer should be migrated to doctrine calls. Currently there's no way to test it properly. In case there won't be a version of a21glossary for TYPO3 9, the a21glossary indexer should be removed.

**Comment by DavidBruchmann** [comment]
Perhaps this is helping to allow both if desired:
https://github.com/DavidBruchmann/wv_file_cleanup/blob/e77d86181e8a1017e799b6651784f8f9d982aca9/Classes/Domain/Repository/FileRepository.php#L245
https://github.com/DavidBruchmann/wv_file_cleanup/blob/e77d86181e8a1017e799b6651784f8f9d982aca9/Classes/Domain/Repository/FileRepository.php#L156

BTW: it's merged, I just took it from my fork now.

Honestly I don't know how it's related to a21glossary, so forgive me if my hint is not applicable.
