### ISSUE TITLE
Implement propper logging

### ISSUE THREAD

**Issue by christianbltr** [teaminmedias-pluswerk/ke_search#255]
As an site administrator I want to know why an indexing process fails in order to be able to fix the problem.

*acceptance criteria*
- A propper logging using the TYPO3 core logging API has been implemented.
- Exceptions which occur especially on database write and read operations and file indexing are catched and logged.

**Comment by christianbltr** [comment]
test

**Comment by kiefer79** [comment]
Logging with TYPO3 Logging API is implemented as follows: 

The "minimum log level" is configurable in extension configuration (default: error)
![kiefer_53](https://user-images.githubusercontent.com/3509209/50288066-19a59200-0465-11e9-9fb5-7e593c48c05f.png)

Log messages matching the configured minimum log level are written into a seperate logfile (e.g. `var/log/typo3_kesearch_3765640ce4.log`) with content like this:

```
Thu, 20 Dec 2018 14:12:20 +0100 [NOTICE] request="d40b2d51fe977" component="TeaminmediasPluswerk.KeSearch.Indexer.IndexerRunner": 
============================
= Indexing process started =
============================ 
Thu, 20 Dec 2018 14:12:21 +0100 [ERROR] request="d40b2d51fe977" component="TeaminmediasPluswerk.KeSearch.Indexer.IndexerRunner": The path to catdoctools is not correctly set in the extension manager configuration. You can get the path with "which catdoc". 
Thu, 20 Dec 2018 14:12:21 +0100 [ERROR] request="d40b2d51fe977" component="TeaminmediasPluswerk.KeSearch.Indexer.IndexerRunner": The path for xls2csv is not correctly set in extConf. You can get the path with "which xls2csv". 
Thu, 20 Dec 2018 14:12:21 +0100 [ERROR] request="d40b2d51fe977" component="TeaminmediasPluswerk.KeSearch.Indexer.IndexerRunner": The path to catppttools is not correctly set in extension manager configuration. You can get the path with "which catppt". 
Thu, 20 Dec 2018 14:12:21 +0100 [WARNING] request="d40b2d51fe977" component="TeaminmediasPluswerk.KeSearch.Indexer.IndexerRunner": Could not index file /var/www/html/web/fileadmin/test/test-invalid.xlsx. 
Thu, 20 Dec 2018 14:12:21 +0100 [WARNING] request="d40b2d51fe977" component="TeaminmediasPluswerk.KeSearch.Indexer.IndexerRunner": Could not index file /var/www/html/web/fileadmin/test/test-invalid.docx. 
Thu, 20 Dec 2018 14:12:21 +0100 [WARNING] request="d40b2d51fe977" component="TeaminmediasPluswerk.KeSearch.Indexer.IndexerRunner": Could not index file /var/www/html/web/fileadmin/test/test-invalid.pptx. 
Thu, 20 Dec 2018 14:12:21 +0100 [WARNING] request="d40b2d51fe977" component="TeaminmediasPluswerk.KeSearch.Indexer.IndexerRunner": Could not index file /var/www/html/web/fileadmin/test/pdf-example-password.original.pdf. 
```

Indexing errors and main indexing db operations are catched, more to come.

The "could not index file..." messages were removed from the indexing report (backend module / sys_log) and replaced by a message pointing to the logfile
![kiefer_54](https://user-images.githubusercontent.com/3509209/50288320-e6173780-0465-11e9-9661-de70ee1ca7a2.png)
