### ISSUE TITLE
Incorrect table name 'tx_kesearch_index, ...' [compat9]

### ISSUE THREAD

**Issue by schnere** [teaminmedias-pluswerk/ke_search#257]
Doctrine QueryBuilder ist quoting the table name which results in an Exception on the search result page.

Exception:
`
An exception occurred while executing 'SELECT SQL_CALC_FOUND_ROWS *, MATCH (title, content) AGAINST ("test") + (1 * MATCH (title) AGAINST ("test")) AS score, IFNULL(ROUND((MATCH (title, content) AGAINST ("test") + (1 * MATCH (title) AGAINST ("test"))) / maxScore * 100), 0) AS percent FROM ´tx_kesearch_index, (SELECT MAX(MATCH (title, content) AGAINST ("test") + (1 * MATCH (title) AGAINST ("test"))) AS maxScore FROM tx_kesearch_index) maxScoreTable´ WHERE 1=1 AND MATCH (title, content) AGAINST ('test*' IN BOOLEAN MODE) AND pid in (216) AND language IN(0, -1) AND (´tx_kesearch_index´.´starttime´ <= 1544884920) AND ((´tx_kesearch_index´.´endtime´ = 0) OR (´tx_kesearch_index´.´endtime´ > 1544884920)) AND (((´tx_kesearch_index´.´fe_group´ = '') OR (´tx_kesearch_index´.´fe_group´ IS NULL) OR (´tx_kesearch_index´.´fe_group´ = '0') OR (FIND_IN_SET('0', ´tx_kesearch_index´.´fe_group´)) OR (FIND_IN_SET('-1', ´tx_kesearch_index´.´fe_group´)))) ORDER BY score desc LIMIT 10 OFFSET 0': Incorrect table name 'tx_kesearch_index, (SELECT MAX(MATCH (title, content) AGAINST ("test") + (1 * MATCH (title) AGAINST'
`

Exception source: ```Classes/Lib/Db.php``` Line 96: 
```php
$resultQuery = $queryBuilder
            ->add('select', $queryParts['SELECT'])
            ->from($queryParts['FROM']) // Line 96
            ->add('where', $queryParts['WHERE']);
```

Typo3 version: 9.5.1

**Comment by schnere** [comment]
There might be a better solution, but this works for my testing purposes:

```diff
104c104
< 
---
>         
252a253
>             
254c255
<                 $fields .= ', IFNULL(ROUND((MATCH (title, content) AGAINST ("'
---
>                 $fields .= ', ROUND( (MATCH (title, content) AGAINST ("'
260c261,266
<                     . '"))) / maxScore * 100), 0) AS percent';
---
>                     . '"))) / (SELECT MAX(MATCH (title, content) AGAINST ("'
>                     . $this->pObj->scoreAgainst
>                     . '") + (1 * MATCH (title) AGAINST ("'
>                     . $this->pObj->scoreAgainst
>                     . '"))) AS maxScore FROM tx_kesearch_index)'
>                     . ' * 100, 0) AS percent';
285c291
<             'FROM' => $table,
---
>             'FROM' => $this->table,
```

**Comment by christianbltr** [comment]
I think this was caused by the "show score" feature. We already removed that (see https://github.com/teaminmedias-pluswerk/ke_search/issues/253). Could you please try again?

**Comment by schnere** [comment]
Yes, that's correct. The problem is not existing in v3.0.1 .
