### ISSUE TITLE
Exception when indexing pages with active extension Gridelements

### ISSUE THREAD

**Issue by wowaTYPO3** [teaminmedias-pluswerk/ke_search#262]
I tested the new version of ke_search (I wanted to show it in my new video course, which is in production).
I created an indexer for **pages**, but when it starts, I get an Exception:

`(1/1) #1461170686 InvalidArgumentException
QueryBuilder::quoteIdentifiersForSelect() could not parse the select (SELECT hidden FROM tt_content as t2 WHERE t2.uid = tt_content.tx_gridelements_container) as parentGridHidden.`

If I deactivate gridelements, everything works.

**Comment by christianbltr** [comment]
This has been fixed in current master. Could you test this using the dev-master version?

**Comment by wowaTYPO3** [comment]
Hm, I did an
`composer req teaminmedias-pluswerk/ke_search:dev-master`
but if I start the indexer, I see:
`Class 'TeaminmediasPluswerk\KeSearch\Indexer\Types\GeneralUtility' not found`

I also tried composer dump-autoload, clearing the caches etc. but it did not work.

**Comment by christianbltr** [comment]
Sorry, my fault! Should be fixed now. Could you try again?

**Comment by wowaTYPO3** [comment]
Yes. now it works! Perfect! Thanks for your fast reaction!
