### ISSUE TITLE
ke_search 3.0.0: different indexer for news has wrong target page

### ISSUE THREAD

**Issue by mfankh** [teaminmedias-pluswerk/ke_search#263]
I set up several indexers for news (ext news). The target page in the search results is always the selected page in the last indexer for news in the list.

* Set at least 2 indexers for news
* For all indexers select an other target page for extension
* Search for news articles
* The target page in the search results is always the selected target page in the last indexer (for all news articles)

**Comment by kiefer79** [comment]
Should also be fixed with #266

**Comment by christianbltr** [comment]
has been fixed in master, will be in version 3.0.2
