### ISSUE TITLE
ke_search 3.0.0: news indexer does not respect storage sysfolder but indexes system-wide

### ISSUE THREAD

**Issue by mfankh** [teaminmedias-pluswerk/ke_search#264]
I set up several indexers for news (ext news). After starting the indexer, the indexer lists all entries of all indexers for news.

* Set at least 2 indexers for news
* Start the indexer
* The indexer lists all news for every indexer (there are total 15 news in different folders)

Here the list:

**Indexer starten**

**Indexer "Indexer Seiten":**
57 pages in 3 languages have been found for indexing.
15 pages have been indexed (40 more had no content).
0 files have been indexed.

*Indexing process for "Indexer Seiten" took 571 ms.*

**Indexer "Indexer News (news)":**
**15 News** have been indexed .

*Indexing process for "Indexer News (news)" took 172 ms.*

**Indexer "Indexer Events (news)":**
**15 News** have been indexed .

*Indexing process for "Indexer Events (news)" took 156 ms.*

**Indexer "Indexer Blog (news)":**
**15 News** have been indexed .

*Indexing process for "Indexer Blog (news)" took 157 ms.*

**Index cleanup:**
0 entries deleted.
Cleanup process took 2 ms.

**Index contains 30 entries.**

**Comment by christianbltr** [comment]
So the thing is, the news indexer does not respect the "starting point" and simply indexes all news records system-wide?

**Comment by mfankh** [comment]
Yes, I think so. The news are stored in different folders. The indexer lists all news in this different folders.
