### ISSUE TITLE
Indexer error

### ISSUE THREAD

**Issue by p380** [teaminmedias-pluswerk/ke_search#272]
When I run indexer on pages, the error below is displayed.

(1/2) Doctrine\DBAL\Exception\DriverException
An exception occurred while executing 'SELECT pages.*, GROUP_CONCAT(CONCAT("#", tx_kesearch_filteroptions.tag, "#")) as tags FROM `pages`, `tx_kesearch_filteroptions` WHERE (pages.uid IN (3) AND pages.tx_kesearch_tags <> "" AND FIND_IN_SET(tx_kesearch_filteroptions.uid, pages.tx_kesearch_tags)) AND (((`pages`.`deleted` = 0) AND (`tx_kesearch_filteroptions`.`deleted` = 0)) AND ((`pages`.`hidden` = 0) AND (`tx_kesearch_filteroptions`.`hidden` = 0))) GROUP BY `pages`.`uid`': 'DB.pages.pid' isn't in GROUP BY

**Comment by rintisch** [comment]
In my case the problem with the same message was that I forgot to specify a record in the field 

    Record sotrage page(s) fo date to be indexed, recursive

(it's descriped in the manual -> Quickstart
I specified the page root as value. But it might be an idea to give a concrete example in the manual to improve clarity...

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
