### ISSUE TITLE
continous `parent_category` loop @ tt_news-indexer

### ISSUE THREAD

**Issue by xerc** [teaminmedias-pluswerk/ke_search#275]
https://github.com/teaminmedias-pluswerk/ke_search/blob/80da19aa01a90b4adfd08a8d0316d670a3cbd69f/Classes/Indexer/Types/Ttnews.php#L346
`        } elseif ($row['parent_category'] > 0 && $row['uid'] != $row['parent_category']) {`

**Comment by christianbltr** [comment]
The old tt_news indexer has been removed, so I'm closing this. FYI: There will be a rewritten one in the future (which has already been implemented in the branch feature-tt-news-indexer but not yet merged.)
