### ISSUE TITLE
"resultsPerPage" not working if >10

### ISSUE THREAD

**Issue by huelsmc** [teaminmedias-pluswerk/ke_search#280]
Hi,
it seems there is an issue with the resultsPerPage field in the plugin configuration.

It works as expected if I change the value there to any number below or equal to 10. But everything above is not working. The max results I'm able to receive in the Frontend is 10. Attached a fdebug of resultrows (while 99 were set in the config).

![27-03-_2019_19-53-20](https://user-images.githubusercontent.com/31927256/55104124-1526f000-50ca-11e9-84a8-f61189351106.jpg)

The issue is probably this part:
ke_search\Classes\Lib\Db.php Lines 106-110
```        $limit = $this->getLimit();
        if (is_array($limit)) {
            $resultQuery->setMaxResults(10);
            $resultQuery->setFirstResult($limit[0]);
        }
```
should be:
```        $limit = $this->getLimit();
        if (is_array($limit)) {
            $resultQuery->setMaxResults($limit[1]);
            $resultQuery->setFirstResult($limit[0]);
        }
```

**Comment by christianbltr** [comment]
fixed in https://github.com/teaminmedias-pluswerk/ke_search/pull/281
