### ISSUE TITLE
[BUGFIX] Classes\Indexer\IndexerRunner.php

### ISSUE THREAD

**Issue by ironAngel2000** [teaminmedias-pluswerk/ke_search#284]
Hi,

on line 629 in the Classes/Indexer/IdexerRunner.php the parameter $table is missing.

**Comment by christianbltr** [comment]
Thanks.As I see it is not only debugging but in fact inserting into the database since the migration to the queryBuilder doctrine database access.

Maybe it would be good to remove the $debug parameter at all from ke_search since every developer will use it's own debugging method when needed.

**Comment by christianbltr** [comment]
fixed with https://github.com/teaminmedias-pluswerk/ke_search/pull/357
