### ISSUE TITLE
Bug with the single quote (') in search input

### ISSUE THREAD

**Issue by NatanaelViau** [teaminmedias-pluswerk/ke_search#285]
Hello, I have a problem with ke_search 3.0.3 on typo3 9.5.0. When I do a search with a string containing an apostrophe (like this -> ') I get this error on screenshot.
Is this problem known? Do you know a solution?

Here is the error message:

An exception occurred while executing 'SELECT SQL_CALC_FOUND_ROWS *, MATCH (title, content) AGAINST ("l'office") + (1 * MATCH (title) AGAINST ("l'office")) AS score FROM `tx_kesearch_index` WHERE 1=1 AND MATCH (title, content) AGAINST ('l'office*' IN BOOLEAN MODE) AND pid in (559,564) AND language IN(0, -1) AND (`tx_kesearch_index`.`starttime` <= 1554886800) AND ((`tx_kesearch_index`.`endtime` = 0) OR (`tx_kesearch_index`.`endtime` > 1554886800)) AND (((`tx_kesearch_index`.`fe_group` = '') OR (`tx_kesearch_index`.`fe_group` IS NULL) OR (`tx_kesearch_index`.`fe_group` = '0') OR (FIND_IN_SET('0', `tx_kesearch_index`.`fe_group`)) OR (FIND_IN_SET('-1', `tx_kesearch_index`.`fe_group`)))) ORDER BY score desc LIMIT 10 OFFSET 0': You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'office*' IN BOOLEAN MODE) AND pid in (559,564) AND language IN(0, -1) AND (`t' at line 1

**Comment by Turbotailz** [comment]
Have also run into this issue. Seems like it could be a major injection issue?

**Comment by christianbltr** [comment]
This has been fixed in version 3.0.4.
