### ISSUE TITLE
No Search Results because 'out of range' match

### ISSUE THREAD

**Issue by chrosey** [teaminmedias-pluswerk/ke_search#288]
Hi there, 

I get this Warning with PHP 7.0.7, MariaDB 10.2 and ke_search 2.7.0 when Searching.

`DOUBLE value is out of range in '1 * (match `databsename`.`tx_kesearch_index`.`title` against ('Searchword'))' in .../typo3_src-8.7.24/typo3/sysext/core/Classes/Database/DatabaseConnection.php line 486`

Where the Number (1) Resembles the value in `basic.multiplyValueToTitle` from Settings.

What can I do to get Results presented?

**Comment by christianbltr** [comment]
Did you try udpdating to the lates version of ke_search?

**Comment by chrosey** [comment]
No, I did not need to.

It was most likey an wrecked up indexer-configuration. 
I tried setting up all indexer-configurations again and the problem was gone.

Therefore I was not able to reproduce the error. When I encounter it again, I will reopen the issue. Thanks for your help so far ;)
