### ISSUE TITLE
feature/newsAttachedFiles - default sorting of files

### ISSUE THREAD

**Issue by TrueType** [teaminmedias-pluswerk/ke_search#290]
for the case index_news_files_mode=0 (file become search results for the own) the default sorting by sortdate=DESC may not be ok. The news search results get sortdate = datetime, which results in much newer values for the files found and the default search results starts with files only.

**Comment by christianbltr** [comment]
When a file attached to a news record is indexed as a separate index record, it gets it's date from the file modification time, not from the news record.

see
https://github.com/teaminmedias-pluswerk/ke_search/blob/2d5f0d96157a369ac8a3c4af579995ecc08d8b1d/Classes/Indexer/Types/News.php#L713

Could you check the file modification time in your case?

**Comment by TrueType** [comment]
Ok. I see. For us we had an upgrade from a very old instance with EXT:tt_news and non-FAL. The files all got newer timestamps during FAL import( or conversion to EXT:news). At that point the files got "newer" modification dates as the news itself. Probably close the issue at this point...

But question may be raised, if news-related-files should get their own timestamp at all? Putting them into a search result of their own is to easier get to the source of a search result, which would else be the news. That is how I see it and then the sortdate may be just coming from the related news. Just thinking...

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
