### ISSUE TITLE
news.indexer reporting - per email

### ISSUE THREAD

**Issue by TrueType** [teaminmedias-pluswerk/ke_search#291]
- indexing related files shows different counts for different index_news_files_mode. For my installation many files could not be indexed, because they just contained images and no text. That is how I explain the "cannot index file" entries in the log. I guess such files are once counted and once not. Prio low.
- the seconds count named in the report do not sum up to the total count of the index run. Prio low. 

>  indexing report
> 
> Finishing time: 09-05-19, 17:14
> 
> Indexer "ke_search Indexer-Konfiguration News1":
> 1153 News and 833 related files have been indexed. 
> Indexing process for "ke_search Indexer-Konfiguration News1" took 226 s. 
> 
> Index cleanup:
> 7 entries deleted.
> Cleanup process took 45 ms.
> Index contains 1153 entries.
> 
> Indexing process ran 3,77 minutes

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
