### ISSUE TITLE
filter options - no multiple OR checkboxes preselection [News]

### ISSUE THREAD

**Issue by TrueType** [teaminmedias-pluswerk/ke_search#294]
EXT:ke_search v3.0.3 (feature branch news related files indexing)
EXT:ke_search_premium (3.0.0)
TYPO3 v.9.5.7
To establish a preselection of the index - news records - with a subset of categories the checkbox filter type with OR is the only way to go, afaik. The filter shows up in the select form plugin and it can be hidden, too, but from the several checkboxes as filter options I can select only one. I can manually manipulate the flexform and set a comma separated list of filter option UIDs there. This works fine. It diesplay the initial search page with the correct number of total index count. Without manual manipulation I can set all checkboxes as marked(filter) and drop any preselection in the search form plugin, but then on initial display the results counter and results shown are not ok.

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
