### ISSUE TITLE
Add Suggest Wizard to Flexforms and TCA

### ISSUE THREAD

**Issue by bernhardberger** [teaminmedias-pluswerk/ke_search#30]
One of the most annoying things in configuring ke_search are the missing suggest wizards...

I took the liberty and added them to where applicable.

Pull request sent.

**Comment by bernhardberger** [comment]
https://github.com/teaminmedias-pluswerk/ke_search/pull/31

**Comment by christianbltr** [comment]
Thanks, merged to master.
