### ISSUE TITLE
Uncaught TYPO3 Exception: Call to a member function warning() on null

### ISSUE THREAD

**Issue by DaniaMeier** [teaminmedias-pluswerk/ke_search#302]
After the update to TYPO3 9.5.7 I get the following error, when trying to index with ke_search:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function warning() on null | Error thrown in file $LOCALPATH/typo3conf/ext/ke_search/Classes/Indexer/Filetypes/Pdf.php in line 121.

Unfortunately it crashes the whole indexer process and refuses to index anything else after that. Since it seems to only be a logger for line 120:
`$errorMessage = 'Content for file ' . $file . ' could not be extracted. Maybe it is encrypted?';
`
I feel like something went wrong there?

If I simply comment line 121 the indexer finishes and seems to index all pdfs, although I do get a warning, that something went wrong.

Oh and this might be related to Issue #158 not sure though.

**Comment by kiefer79** [comment]
I checked that. It's a bug. The `pObj` instance that contains the logger is not available at this point. I'll make a bugfix that will be available in the next release. 
This seems not to be related to #158
