### ISSUE TITLE
File indexer: exclude folder pattern?

### ISSUE THREAD

**Issue by ursbraem** [teaminmedias-pluswerk/ke_search#306]
We have some pre-deleted files in "recycler" folders, `_recycler_`. Obviously, they shouldn't appear in search results.

Will the file indexer index them as well and if so, is it possible to exclude them?

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
