### ISSUE TITLE
Add depth option to indexer config

### ISSUE THREAD

**Issue by vmans** [teaminmedias-pluswerk/ke_search#307]
The third parameter of getTreeList sets the depth. Would be a nice feature in the indexer for defining subpages without parentpages to be indexed.

So, change this
Classes/Indexer/IndexerBase.php
`public function getPagelist($startingPointsRecursive = '', $singlePages = '')`
`...`
`$pageList .= $this->queryGen->getTreeList($pid, 99, 0, '1=1') . ',';`

into something like this
`public function getPagelist($startingPointsRecursive = '', $depth=0, $singlePages = '')`
`...`
`$pageList .= $this->queryGen->getTreeList($pid, 99, $depth, '1=1') . ',';`

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
