### ISSUE TITLE
Sorting Option Score not possible

### ISSUE THREAD

**Issue by igaumann** [teaminmedias-pluswerk/ke_search#308]
In function TeaminmediasPluswerk\KeSearch\Lib\Sorting->renderSorting()
$this->pObj->sword is always empty, so it not possible to render score as a sortingOption in FE.

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
