### ISSUE TITLE
Out of memory fatal error in the backend

### ISSUE THREAD

**Issue by guelzow** [teaminmedias-pluswerk/ke_search#309]
Hi everyone.

**You will get an out of memory fatal in the backend when:**
- you have over 1000 indexed records (news and pdfs with lots of text)
- select *indexed content* in the backend module

**Setup:**
- Php 7.2
- TYPO3 9.5.7
- ke_search 3.0.4

**What is happening inside the code**
[Here](https://github.com/teaminmedias-pluswerk/ke_search/blob/v3.0.4/Classes/Controller/BackendModuleController.php#L580) the controller stitches together the content to a potentially very large string, and runs out of memory.

Tobi

**Comment by christianbltr** [comment]
Moved to https://github.com/tpwd/ke_search/issues/100
