### ISSUE TITLE
Add subtitle of page to search-list title

### ISSUE THREAD

**Issue by MichiSpandl** [teaminmedias-pluswerk/ke_search#311]
Hello,

I need the subtitle next to the pagetitle in the search results - how can I do this? Do I really need to write a full new PageIndexer? Has anyone a solution for me? It seems I'm a little bit slow today....

Thanks,
Michi

**Comment by ayacoo** [comment]
Hi @MichiSpandl , old issue but just for documentation:

There is a hook to modify entries before they are indexed: https://github.com/teaminmedias-pluswerk/ke_search/blob/master/Classes/Indexer/Types/Page.php#L607

There is no need for a custom indexer.

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
