### ISSUE TITLE
Results counted too often in filter form

### ISSUE THREAD

**Issue by FlyKasual** [teaminmedias-pluswerk/ke_search#312]
Version: 2.7.0
TYPO3-Version: 8.7.1

When automatically assigning tags to to subpages of a page, those tags are counted per language in the filter form plugin.
Example: I have a site with two languages (EN and DE). I create the pages 'Filter', 'Shoes', and 'Stilettos' as a subpage of 'Shoes'. I create a filter 'type' as a checkbox, and for that a filter option 'shoes' and assign it to all subpages of 'Shoes'. Thus, 'Stilettos' is automatically tagged 'shoes'. I know translate all these to German. I have the 'Seachbox and Filters' plugin on the page 'Filter'. There, I see that there are two results should I check the 'Shoes', even though there is only one page tagged as 'shoes'. In the Faceted Search backend module I also see that the page is tagged twice. If I disable the filter option in my secondary language, all numbers are correct.

**Comment by saneinsaner** [comment]
That’s because \TeaminmediasPluswerk\KeSearch\Indexer\IndexerBase::addTagsToRecords is not respecting the current language when fetching filter options.
As workaround you can use the following hook:
```class KeSearchHook
{
    public function modifyPagesIndexEntry(
        $uid,
        $pageContent,
        &$tags,
        $cachedPageRecords,
        $additionalFields,
        $indexerConfig,
        $indexEntryDefaultValues,
        $pObj
    ) {
        // bugfix: ke_search doesn’t respect sys_language_uid for filter options
        $tagsArray = GeneralUtility::trimExplode(',', $tags, true);
        $tags = implode(',', array_unique($tagsArray));
    }
}```
