### ISSUE TITLE
TYPO3 8 does not recognize that there is another 2.8 version available

### ISSUE THREAD

**Issue by rowild** [teaminmedias-pluswerk/ke_search#314]
I am not sure, if this is at all possible, but I thought I mentioned it here. I have TYPO3 8.7.27 with ke_search 2.8.1 installed. After ugrading the extensions, TYPO3 should recognize that there is a ke_search 2.8.2 available. But it doesn't.

Any idea, why?

**Comment by christianbltr** [comment]
Are you in composer mode or in classic / extension manager mode?

**Comment by rowild** [comment]
Classic mode

**Comment by christianbltr** [comment]
As far as I know it is not possible to upload updates of older branches of extensions to TER. Since 2.8.2 has been released after 3.0, it was not possible to upload this version to TER.

**Comment by rowild** [comment]
I didn't know that! Thank you for telling me!

(Closing the issue.)
