### ISSUE TITLE
ke_search url routeEnhancers

### ISSUE THREAD

**Issue by LPGGNecromant** [teaminmedias-pluswerk/ke_search#320]
How to route with ke_search and config.yaml?

Is there even an controller for it?

**Comment by rowild** [comment]
A much requested topic, already when there was realurl... teaminmedias: You already promised various times that you are going to provide example snippets. Please live up to your promises! Thank you!

**Comment by martingebhardt** [comment]
Yes, that's also a big issue for me, I also need valid urls.

**Comment by DavidBruchmann** [comment]
duplicate of #279

**Comment by christianbltr** [comment]
Closing this as a duplicate of #279, please have a look at https://github.com/teaminmedias-pluswerk/ke_search/issues/279#issuecomment-738775432
