### ISSUE TITLE
Results from news have no url / are not linked

### ISSUE THREAD

**Issue by martingebhardt** [teaminmedias-pluswerk/ke_search#323]
I installed the extension tx_ke_search in TYPO3 9.5.11. I also have extension tx_news and the result list also shows all pages and news entries. However, only the news headlines are not linked. Has anyone had the same problem?

The parameter ['url'] is empty.

![Bildschirmfoto 2019-11-12 um 14 26 54](https://user-images.githubusercontent.com/16338983/68675682-aadb9680-0558-11ea-9059-04e9e8857f4d.JPG)

![Bildschirmfoto 2019-11-12 um 14 30 52](https://user-images.githubusercontent.com/16338983/68675877-19b8ef80-0559-11ea-8361-cfa0bdd6c255.JPG)

**Comment by christianbltr** [comment]
Maybe the "Target Page" you selected in the indexer configuration is hidden? That could lead to this behavior.

**Comment by martingebhardt** [comment]
@christianbltr Great! That was the problem. Thank you very much for your help and the ticket can therefore be closed. This is solved and was not an error of the extension.
