### ISSUE TITLE
showSortInFrontend = false shows Sort in Frontend

### ISSUE THREAD

**Issue by Cabanaramma** [teaminmedias-pluswerk/ke_search#324]
If showSortInFrontend is set false, but sortByVisitor has a value, the sorting is visible in frontend. In the template SearchForm.html checks a if condition if {conf.sortByVisitor} is set, but it should check if {conf.showSortInFrontend} is true, too.

**Comment by christianbltr** [comment]
I could not reproduce that issue in current ke_search master in TYPO3 11. If `showSortInFrontend` is not set in the FlexForm, no sorting links are displayed in the frontend, even if `sortByVisitor` has a value.

ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
