### ISSUE TITLE
PHP 7.3 deprecation notice: strstr() in `buildPiVarsTagsAgainst()`

### ISSUE THREAD

**Issue by sommerhit76** [teaminmedias-pluswerk/ke_search#325]
The method `buildPiVarsTagsAgainst()` in `TeaminmediasPluswerk\KeSearch\Lib\Searchphrase` doesn't seem to work with PHP 7.3. I get the following deprecation notice for `strstr()` because `$subtag` doesn't exist in line 226.

`PHP Runtime Deprecation Notice: strstr(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in public/typo3conf/ext/ke_search/Classes/Lib/Searchphrase.php line 226`

For me this small change seems to work – don't know if that causes other trouble though...

```
@@ -223,7 +223,7 @@
                     }
                 } else {
                     // Don't add the tag if it is already inserted by preselected filters
-                    if (!empty($tag) && strstr($tagsAgainst[$key], $subtag) === false) {
+                    if (!empty($tag)) {
                         $tagsAgainst[$key] .= ' +"'
                             . $tagChar
                             . $queryBuilder->quote($tag)
```

**Comment by boettner-it** [comment]
Have this one too and the suggested fix works on my side too.

**Comment by ulrike-cosmoblonde** [comment]
I had the same problem.
I assume $subtag is just not the correct variable, but $tag needs to be used instead?

Can you please adjust this line so ke_search works on PHP 7.3?

**Comment by DavidBruchmann** [comment]
@ulrike-cosmoblonde you might be right, $subtag is only defined in the loop above and is not triggered in the else-part: https://github.com/teaminmedias-pluswerk/ke_search/blob/fb7f777ce8f65f8d4e2dc5311b0e1a69a03e63c5/Classes/Lib/Searchphrase.php#L213
