### ISSUE TITLE
Enhancement: modify filelink rendering if FAL

### ISSUE THREAD

**Issue by phil64** [teaminmedias-pluswerk/ke_search#331]
Hi,

In function getResultLinkConfiguration of SearchHelper.php, it would be better to write:
`$linkconf['parameter'] = 't3://file?uid='.$resultRow['orig_uid'];`
instead of
`$linkconf['parameter'] = $fileObject->getPublicUrl();`

So, the rendering of the "PublicUrl" of the file is still managed by the typolink functionnality.

**Comment by christianbltr** [comment]
Thanks!
