### ISSUE TITLE
[FEATURE] Prevent indexing of "header" for custom elements in page indexer

### ISSUE THREAD

**Issue by r3h6** [teaminmedias-pluswerk/ke_search#339]
Currently for the page indexer the "header" column gets indexed regardless if the "header" is renderer in frontend or not.
A Hook after adding the "header" to the content could solve this problem.

**Comment by christianbltr** [comment]
I'm not sure if I understand you.

Setting the header of a content element to type "hidden" prevents indexing the header (see Screenshot).

Could you explain a bit more what you want to achieve?

![Bildschirmfoto von 2020-04-11 16-57-15](https://user-images.githubusercontent.com/11410553/79047265-d7820000-7c15-11ea-8d89-8b24abe1c014.png)

**Comment by christianbltr** [comment]
I'm closing this here. Feel free to open another issue at https://github.com/tpwd/ke_search/issues if the proposed solution does not work for you.
