### ISSUE TITLE
[BUG] Filter rendering type

### ISSUE THREAD

**Issue by SassCoder** [teaminmedias-pluswerk/ke_search#340]
The filter rendering type "Text Links" generates the following error:

`Class 'TeaminmediasPluswerk\KeSearch\Lib\Textlinks' not found`

**Comment by christianbltr** [comment]
see also https://github.com/teaminmedias-pluswerk/ke_search/issues/269

**Comment by christianbltr** [comment]
closed with https://github.com/teaminmedias-pluswerk/ke_search/commit/418855b8b6326cb8b54b3143c18ab9fe7f53d0c0
