### ISSUE TITLE
Data too long for column 'details' in sys_log 

### ISSUE THREAD

**Issue by AstCommodore** [teaminmedias-pluswerk/ke_search#342]
In case of a huge number of indexer configuration records (> 350), the BE module of KE search could throw an error when writing to the sys_log table:

The field 'details' is of SQL type 'text'  and therefor too small for this huge amount of logging information. Maybe the logging information per record could get reduced and/or an extended logging of these information could be done in the KE search own log.

Aside this issue, KE search is a powerful and well done extension.
Thank you for doing great work!

**Comment by christianbltr** [comment]
Thanks for reporting!
The report is now cut at 60000 characters which fits into the details column.
If you need more logging information, you can adjust the logging level in the extension settings of ke_search. A log file will be written to the log directory of TYPO3.
