### ISSUE TITLE
Wrong calculation of pagination in getSearchResultByMySQL

### ISSUE THREAD

**Issue by warehousebg** [teaminmedias-pluswerk/ke_search#343]
/* @TODO-FIXES: folowing code produce wrong calculation of pagination
        $limit = $this->getLimit();
        if (is_array($limit)) {
            $resultQuery->setMaxResults(10);
            $resultQuery->setFirstResult($limit[0]);
        }
        */

**Comment by christianbltr** [comment]
getLimit() returns an array containing the start value in key 0 and the limit in in key 1. This can also be adjusted by third-party-hooks. See https://github.com/teaminmedias-pluswerk/ke_search/blob/e00e8accce7765e1ecbc2cbaa6c7f33723abeaba/Classes/Lib/Db.php#L498

The limit is not supposed to be hardcoded to 10, so I'm closing this.
