### ISSUE TITLE
Additional configuration extraction is required in moveFlexFormDataToConf

### ISSUE THREAD

**Issue by warehousebg** [teaminmedias-pluswerk/ke_search#344]
public function moveFlexFormDataToConf($traceData = false)
    {
        // don't move this to init
//         $this->pi_initPIflexForm();

    	// @TODO-FIXES: bug fix - the original code did not allow taking of the settings from the pi_flexform
        $piFlexForm = $this->cObj->data['pi_flexform'];
        if ($traceData && is_array($piFlexForm['data'])) {
            foreach ($piFlexForm['data'] as $sheetKey => $sheet) {
                foreach ($sheet as $lang) {
                    foreach ($lang as $key => $value) {
                        // delete current conf value from conf-array
                        // when FF-Value differs from TS-Conf and FF-Value is not empty
                        $value = $this->fetchConfigurationValue($key, $sheetKey);
                        if ($this->conf[$key] != $value && !empty($value)) {
                            unset($this->conf[$key]);
                            $this->conf[$key] = $this->fetchConfigurationValue($key, $sheetKey);
                        }
                    }
                }
            }
        } elseif (is_array($piFlexForm)) {
            foreach ($piFlexForm as $key => $value) {
                // delete current conf value from conf-array
                // when FF-Value differs from TS-Conf and FF-Value is not empty
                if ($this->conf[$key] != $value && !empty($value)) {
                    unset($this->conf[$key]);
                    $this->conf[$key] = $value;
                }
            }
        }
        
    }

**Comment by warehousebg** [comment]
In addition the following has to be changed in the init() 

 // make settings from flexform available in general configuration ($this->conf)
        $this->moveFlexFormDataToConf();

        // in pi2 (the list plugin) fetch the configuration from pi1 (the search
        // box plugin) since all the configuration is done there
        if (!empty($this->conf['loadFlexformsFromOtherCE'])) {
            $data = $this->pi_getRecord('tt_content', intval($this->conf['loadFlexformsFromOtherCE']));
            $this->cObj->data = $data;
            $this->pi_initPIflexForm();
            $this->moveFlexFormDataToConf(true);
        }

**Comment by christianbltr** [comment]
Hello,
thanks for your contribution. Could you explain a bit more which problem you are adressing and how to reproduce it?

**Comment by christianbltr** [comment]
I'm closing this here. Feel free to open another issue at https://github.com/tpwd/ke_search/issues it is still an issue for you.
