### ISSUE TITLE
Label for {pagebrowser.next}

### ISSUE THREAD

**Issue by timofo** [teaminmedias-pluswerk/ke_search#35]
Instead of "nächste" the name auf {pagebrowser.next} is "Suche".
LLL:EXT:ke_search/pi1/locallang.xml:pagebrowser_next is "nächste" but not {pagebrowser.next}
Also the label for "vorherige" is "Suche".
I can't find any "Suche" in all of the files??

**Comment by fjacobi** [comment]
This will be fixed in the coming release.

https://github.com/teaminmedias-pluswerk/ke_search/issues/28

**Comment by christianbltr** [comment]
Version 2.2.0 has been released today.
