### ISSUE TITLE
Problem classes loading 

### ISSUE THREAD

**Issue by lstephanws** [teaminmedias-pluswerk/ke_search#351]
Hi,

After switching website to composer, the extension stopped working. There seems to be some class loading issues.

version : 2.8.1
TYPO3 8.7.32

Any idea ?

Thanks

**Comment by christianbltr** [comment]
Hi, 

I'm not aware of ony problems with composer installation in this version. We used to install ke_search in TYPO3 8 with composer without any problems. Did you try "composer dump-autoload"? What error messages do you get?

**Comment by ismab** [comment]
Hi, 

Thanks for your help.

To bring a precision, here is an error occurring while passing on composer (after composer dump-autoload) on TYPO3 8.7.32 and Ke_search 2.8.1:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function modifyPageContentFields() on null | Error thrown in file /web/typo3conf/ext/ke_search/Classes/indexer/types/class.tx_kesearch_indexer_types_page.php in line 419.`
 
The lines concerned in class.tx_kesearch_indexer_types_page.php are : 

```
418: $_procObj = &\TYPO3\CMS\Core\Utility\GeneralUtility::getUserObj($_classRef);
419: $_procObj->modifyPageContentFields($fields, $this);
```

$_classRef is a valid path for a custom indexer loaded in the composer.json autoload (and which used to work without composer)

**Comment by christianbltr** [comment]
So it's your custom class which cannot be found? Then I think this is not a ke_search related bug.
The points I would have a look at are:
How do you register the hook?
What does your composer.json of the extension containing the hook look like?
How is the file structure and class naming?
Is your hook function found when you call it from other places?

**Comment by christianbltr** [comment]
Since this seems not to be related to ke_search itself (see last comment), I'm closing this.
