### ISSUE TITLE
ckeditor adds empty paragraphs 

### ISSUE THREAD

**Issue by nom10s** [teaminmedias-pluswerk/ke_search#353]
Ckeditor in ke_search 2.8.1 / TYPO3 8.7.24 adds empty paragraphs in the backend fields textForResults and noResultsText.

This solved the issue for me: In typo3conf/ext/ke_search/pi1/flexform_pi1.xml, section textForResults -> TCEforms -> config (line 65 and 89/90) add

`<enableRichtext>1</enableRichtext>`

This core issue gave me the idea: https://forge.typo3.org/issues/80778 brings

Kind regards
Stefan

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
