### ISSUE TITLE
No recursiv Indexing of tt_address folders 

### ISSUE THREAD

**Issue by MondtT** [teaminmedias-pluswerk/ke_search#359]
T3 V 9.5.18
ke_search V 3.1.3

If you try indexing pagefolders with tt_address data. It's impossibel to do that recursively.
- If you choose 1 folder - 1 single subfolder will be indexed
- If you choose multiple folders - the first chosen folder will be indexed
- If you create mutiple indexer for different adress folders - the last indexer with one folder will be indexd

How indexing of tt_address page-folders recursively can be done?
Can it be configured by TS?
![20200629_T3_ke_search_recursiv01](https://user-images.githubusercontent.com/67581238/86003559-42232a80-ba12-11ea-8270-3568cf49cb6f.JPG)

**Comment by christianbltr** [comment]
This is fixed now, will be in the next version.

related to https://github.com/teaminmedias-pluswerk/ke_search/issues/374

fixed with https://github.com/teaminmedias-pluswerk/ke_search/commit/a293e8942e00cfff4043ae5e336b309e7d30bef2
