### ISSUE TITLE
Numbers and certain terms cancel out search results with enableExplicitAnd = 1 

### ISSUE THREAD

**Issue by localhorst** [teaminmedias-pluswerk/ke_search#360]
Error occurs in the serach result list.

TYPO3 9.5
ke_search 3.1.3

multiplyValueToTitle = 5
searchWordLength = 3
enablePartSearch = 1
enableExplicitAnd = 1

Indexer for News
Indexer for Pages

There is a content element and a news item with the title "13 Antworten von Lorem Ipsum Heiner Mueller"
When we search for the exact title, we get no results
When we search for "Antworten Lorem Ipsum Heiner Mueller", we get the two entries (tt_content and tx_news)
When we search for "13 Heiner Mueller", "von Heiner Mueller" (and so on), we get no results.

So there are no results if we use "13" or "von" in the search phrases.
If I set enableExplicitAnd = 0, the results are shown.

I am happy to provide you with more data if asked.

**Comment by christianbltr** [comment]
Did you adjust ft_min_word_len as described in https://docs.typo3.org/p/teaminmedias-pluswerk/ke_search/master/en-us/Configuration/SearchWordLength.html ?

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
