### ISSUE TITLE
Support for extension container / hook in page indexer

### ISSUE THREAD

**Issue by akiessling** [teaminmedias-pluswerk/ke_search#362]
The page indexer has a hardcoded support for gridelements extension to skip the indexing, if the container element is e.g. deleted. It would be great to switch this out with a hookable implementation, so extensions like https://github.com/b13/container could also be supported out-of-the-box or via an adapter extension.

**Comment by christianbltr** [comment]
There's now support for EXT:container built in as well as for EXT:gridelements. An additional hook now allows other extensions to add custom checks if content elements should be indexed or not.

**Comment by akiessling** [comment]
Wow, that was fast! :) Thank you so much!
