### ISSUE TITLE
News Indexer - Category Selection doesn't contain Category Uids

### ISSUE THREAD

**Issue by MichiSpandl** [teaminmedias-pluswerk/ke_search#363]
In Version 3.1.6 if I'd like to index news only from a special category nothing (news) is indexed at all - I checked what is in $this->indexerConfig['index_extnews_category_selection'] bit I only get the number of selected categories instead of the category ids. I think it would be correct if you get the uids because of the line 
`if (GeneralUtility::inList($this->indexerConfig['index_extnews_category_selection'], $catUid)`
or am I wrong? 
Thank you"

**Comment by christianbltr** [comment]
Thank you for reporting this issue. This may be a regression in ke_search 3.1.6. Could you try version 3.1.5?

**Comment by cepheiVV** [comment]
@christianbltr 

**PR:** https://github.com/teaminmedias-pluswerk/ke_search/pull/368

I fixed this for my env. 
Can you have a look if this works for you and/or let me know if this needs further changes?

**Comment by christianbltr** [comment]
Thanks, the PR fixes the issue from my point of view.
