### ISSUE TITLE
SQL error: 'Unknown column 'tx_kesearch_resultimage' in 'field list''

### ISSUE THREAD

**Issue by enem-frir** [teaminmedias-pluswerk/ke_search#364]
Hello,

we're using **ke_search 2.8.3** in **TYPO3 7.6.23**.

The Page properties can't be changed, because if we want to safe our changes, we're getting following error:
SQL error: 'Unknown column 'tx_kesearch_resultimage' in 'field list''.

We could try to update the TYPO3 version to 7.6.46.

Any idea how we can fix this?

Thanks in advance.

**Comment by christianbltr** [comment]
Seems as if the field "tx_kesearch_resultimage" is missing in the database. Did you do the "Compare Database" action in the Install Tool?

**Comment by enem-frir** [comment]
> Seems as if the field "tx_kesearch_resultimage" is missing in the database. Did you do the "Compare Database" action in the Install Tool?

Thanks for your help. 
Comparing the database in the install tool worked. We were able to create the missing fields! :)
