### ISSUE TITLE
ke_search v2.8.3 not finding words with . (dots) in it.

### ISSUE THREAD

**Issue by lsascha** [teaminmedias-pluswerk/ke_search#369]
Still using TYPO3 v8 unfortunately so i am stuck to ke_search v2.*
tested with MySql v5.7.30 and v5.7.31

Issue:
When searching for words that include dots like `A.B.C.D.` it does not find any results about it, even if its successfully indexed.
That can be confirmed when i search for an additional word that appears also in the index of this one indexed page like `A.B.C.D something` it will find "something" but does also highlight "A.B.C.D." in the result shown.

wrapping the `A.B.C.D.` word with anything does not help. so `+"A.B.C.D"` with or without `"` and/or `+` does still not show any results.

setting
```
[mysqld]
ft_min_word_len = 1
```
with or without also setting in the extension `basic.searchWordLength = 1` does also not help.

according to a slack chat with @christianbltr it does work with dev-master of ke_search on MariaDB 10.3.22
but since TYPO3 v8 is not officially supported with ke_search >= v3 this does not really help.

Maybe if someone could hint me into a commit which solves this, i could backport it to v2?

_As a side-node:_
Searching for words that contain a `-` does also not show these words in the results. like `one-word`, but at least here i was able to wrap it with `"` so i made a small hook which looks for words with a `-` and no spaces and wraps these with `""`
which might not be optimal, but at least it then shows these words.

But as i wrote - the issue with dots is not solvable like this.

**Comment by DavidBruchmann** [comment]
Did you try to search for `A\.B\.C\.D\.`?

**Comment by lsascha** [comment]
yes. i tried that as well. did not help.

**Comment by ped** [comment]
I am experiencing the same problem. Any Updates on this?

**Comment by christianbltr** [comment]
Could you try switching to MyISAM? (I'm assuming you are using InnoDB as storage engine for the table tx_kesearch_index since this was the default in ke_search 2.8.3.)

* Add ENGINE = MyISAM; to the table definition (see https://github.com/teaminmedias-pluswerk/ke_search/blob/d08ad872f62e1efdcd803a84a7bdbd3c77ca2535/ext_tables.sql#L106)
* Execute "Compare database"
* Run the indexer

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
