### ISSUE TITLE
Backend error when indexing in version 3.3.0

### ISSUE THREAD

**Issue by dphillips479** [teaminmedias-pluswerk/ke_search#379]
With version 3.3.0 I get an error when I want to start indexing.

(1/1) TypeError
Argument 1 passed to TeaminmediasPluswerk\KeSearch\Lib\SearchHelper::makeSystemCategoryTags() must be of the type string, null given, called in /var/www/goldgas/www.goldgas.de/htdocs/site/goldgas/web/typo3conf/ext/ke_search/Classes/Indexer/IndexerBase.php on line 239

When I downgrade back to version 3.2.0 it works again.

**Comment by christianbltr** [comment]
Version 3.3.1 has been released which should fix this issue. Could you test it?

**Comment by dphillips479** [comment]
Just tested it with  version 3.3.1 and works fine now.
