### ISSUE TITLE
No own ICONS are possible in search result. 

### ISSUE THREAD

**Issue by quadronet** [teaminmedias-pluswerk/ke_search#385]
Hello, this configuration don´t work:

plugin.tx_kesearch_pi2.resultListTypeIcon.page.file = fileadmin/icons/html.png
plugin.tx_kesearch_pi2.resultListTypeIcon.file_doc.file = fileadmin/icons/fileadmin/icons/doc.png
plugin.tx_kesearch_pi2.resultListTypeIcon.file_pdf.file = fileadmin/icons/pdf.pdf

Zeige Ergebnistyp-Icon? is set

ke_search: 3.3.1 , TYPO3 9.5.23

What is wrong?

Best regard´s!

**Comment by christianbltr** [comment]
I just tested this, it works as expected (tested with ke_search 3.3.1 on TYPO3 10.4.9).

Did you disable " Show file preview instead of result icon if possible?"
Did you put the typoposcript into the "Setup" section (not "Constants")?

**Comment by christianbltr** [comment]
I'm closing this here. Feel free to open another issue at https://github.com/tpwd/ke_search/issues it is still an issue for you.
