### ISSUE TITLE
Can't place results plugin

### ISSUE THREAD

**Issue by hilburger** [teaminmedias-pluswerk/ke_search#394]
Hey guys! 

I have a problem in a YPO3 10.4.13 installation. 
After placing the search box plugin and configuring the search folder I can't place the results plugin. 
I choose he search box plugin in side the resuls plugin but I always get an error while saving that I am still missing the required field (loadFlexformsFromOtherCE). But that's exactly what I have done. Does anybody know this problem?
It's the current ke_seach version 3.4.2. 

One thing I did wrong was to accidently install the hooks-plugin (ke_search_hooks 3.2.0) at first. 
There I have had he problem for he first time. 
Then I uninstalled it via Composer and installed the right extension ke_search. 
But still I get the error with the rich extension. 

Results are the same on CHrome and Firefox (MacOS Catalina)

**Comment by hilburger** [comment]
Little Update: 
Re-installing the hooks-examples did not help. 

What helped at first: 
I managed to create the results plugin by filling out the mandatory field loadFlexformsFromOtherCE and then by switching to another content type without saving and back. 

Why it did not solve he problem: 
I have the same problem with the indexer configuation in list mode - now it's the mandatory field  storagepid . 
Unluckily I can't do the same trick as with the plugin here.

**Comment by christianbltr** [comment]
related to https://github.com/teaminmedias-pluswerk/ke_search/issues/397

**Comment by christianbltr** [comment]
related to https://github.com/teaminmedias-pluswerk/ke_search/issues/395

**Comment by christianbltr** [comment]
Closing this as this has been fixed with TYPO3 10.4.14.
