### ISSUE TITLE
Cant Save New Indexer in TYPO3 10.4.13

### ISSUE THREAD

**Issue by chriskrj** [teaminmedias-pluswerk/ke_search#395]
I am trying to save new Indexer in TYPO3 10.4.13 with ke_search 3.4.2 and php Version 7.4.15.
the storage field is marked as required what it should be, but when i select the sys_folder for the search storage data its not set correctly. The field still has no selection. So i cant save my created Indexer because required fields are not set. 
When i change the Indexer type the previewsly selected storage is taken over. But this should only be a work around for now. 

I tried changing ke_search version 3.4.1,3.4.0 3.3 still the same. 
then i changed the php version to 7.3 still the same.
Then i changed my TYPO3 Version to 10.4.12 and then it worked again as expacted. So something is messing up the select field from ke_search indexer form in 10.4.13 of TYPO3

![Bild eingefügt am 2021-2-19 15-56](https://user-images.githubusercontent.com/23551989/108525124-0eae4c80-72d0-11eb-85b1-08c29e0f3ee7.png)
![Bild eingefügt am 2021-2-19 16-14](https://user-images.githubusercontent.com/23551989/108525126-0f46e300-72d0-11eb-980c-bba6d282e13d.png)

**Comment by hilburger** [comment]
Looks like a TYPO3 bug in 10.4.13 - check here with Nikolas what we have found: 
https://twitter.com/pulponair/status/1363240150076112898

Same problem with creating the results plugin: 
https://github.com/teaminmedias-pluswerk/ke_search/issues/394

**Comment by peerlight** [comment]
see https://forge.typo3.org/issues/93574

**Comment by chriskrj** [comment]
Then i close this issue. Its not directly from ke_search Ext.

**Comment by christianbltr** [comment]
related to https://github.com/teaminmedias-pluswerk/ke_search/issues/397
