### ISSUE TITLE
Typo3 Update 10.4.13 breaks ke_search Flexform

### ISSUE THREAD

**Issue by saschaluebeck** [teaminmedias-pluswerk/ke_search#397]
Hi there,

the latest Update on Typo 10 (10.4.13) breaks the flexform for index configuration. I'm not able to save the config. It says, the field "storagepid" is not set but I filled the field as usual. So I can't save my indexer config.

I tried to fill the field in the db, which is working. After that the field is filled with the folder an I can use the form as usual. But when I start an index process, there appears a database error.

_Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'SELECT `pages`.* FROM `pages`, `tx_news_domain_model_news` WHERE (`pages`.`uid` IN ()) AND (`pages`.`no_search` <> ?) AND (`pages`.`hidden` = ?) AND (`pages`.`deleted` = ?) AND (`tx_news_domain_model_news`.`pid` = `pages`.`uid`)' with params [1, 0, 0]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) AND (`pages`.`no_search` <> ?) AND (`pages`.`hidden` = ?) AND (`pages`.`delet' at line 1 | Doctrine\DBAL\Exception\SyntaxErrorException thrown in file C:\laragon\www\webpage\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php in line 83. Requested URL: https://webpage.test/typo3/index.php?route=%%2Fmodule%%2Fweb%%2FKeSearchBackendModule&token=--AnonymizedToken--&id=38&do=startindexer_

When I go back to 10.4.12 the form works correct.
Don't know what breaks the extension in the last update. Only entries in changelog could be:

https://get.typo3.org/release-notes/10.4.13

- 2020-12-22 53fc5f9a99 [BUGFIX] Skip broken flexform in form upgrade wizard (thanks to Ayke Halder)
- 2021-01-11 9e6ed87d7e [BUGFIX] Hide deleted flexform section in DOM (thanks to Andreas Fernandez)

But maybe I miss something.

Thanks and best,
Sascha

**Comment by lukas-maxheim** [comment]
I can reproduce the problem as well.

**Comment by bluhmsysteme** [comment]
Same here!

**Comment by ste101** [comment]
Works in 10.4.14 again.

**Comment by lukas-maxheim** [comment]
I can confirm the statement of @ste101 - works again!

**Comment by christianbltr** [comment]
Closing this as this has been fixed with TYPO3 10.4.14.
Thanks for the feedback.
