### ISSUE TITLE
Bug: Searchbox causes all GET parameters to be removed from any URL

### ISSUE THREAD

**Issue by christophbee** [teaminmedias-pluswerk/ke_search#399]
## Description:
When searchbox for ke_search is added to the menu bar on every page all GET parameters from any url get removed by any javascript. When I remove the searchbox everything is fine. 

## Prerequisites:
TYPO3 v.10.4.12
ke_search v 3.4.2

## Steps to reproduce:
Typoscript
```
lib.searchbox = COA_INT
lib.searchbox.10 < plugin.tx_kesearch_pi1
```
Fluid template
`<f:cObject typoscriptObjectPath="lib.searchbox" />`

## Result: 
Calling **example.com/any-path?aparam=1&another-param=true** results in **example.com/any-path**

**Comment by christianbltr** [comment]
Thanks for pointing this out. This is now fixed. The URL will only be rewritten if the search is not empty, that means a search parameter is given. This should only be the case on search result pages.

BTW the javascript command to replace the URL is only necessary if you use speaking URLs and can be removed in custom templates if not needed.
