### ISSUE TITLE
Version 1.99.3 not on Packagist

### ISSUE THREAD

**Issue by rkiciak** [teaminmedias-pluswerk/ke_search#4]
It seems like the latest version 1.99.3 is [not available via Packagist](https://packagist.org/packages/teaminmedias-pluswerk/ke_search). Could you please update your package over there?

**Comment by teaminmedias-pluswerk** [comment]
I looked into that and I'm not sure why packagist is not updating the package. Version 1.99.3 is set as a release on github.com, 1.99.3 is set in composer.json as version number, I created a webhook for immediate updating and I even clicked "UPDATE" on the packagist administration site for ke_search.

**Comment by christianbltr** [comment]
Version 1.99.4 is now on packagist.
