### ISSUE TITLE
Unset TT News Indexer

### ISSUE THREAD

**Issue by mikestreety** [teaminmedias-pluswerk/ke_search#401]
Thanks for the great work!

We have a custom modification of `tt_news` which I created an indexer. The update to 3.5.0 is now interfering with this as they share the table name.

Is there a way I can disable the TTNews indexer that comes with the extension?

Thanks

**Comment by christianbltr** [comment]
Yes. The tt_news indexer is registered in the TCA definition file for the indexer configuration:

https://github.com/teaminmedias-pluswerk/ke_search/blob/1c7b7a206bbd24439f55a8ecb9ad1a2bf874cc74/Configuration/TCA/tx_kesearch_indexerconfig.php#L91

You can overwrite TCA definitions in your own extensions and remove (unset) that configuration. See also https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ExtendingTca/Index.html
