### ISSUE TITLE
No indexing of a language with cyrillic letters 

### ISSUE THREAD

**Issue by windups76** [teaminmedias-pluswerk/ke_search#402]
A Website in German, English and Russian Language exist. The page is translated, the search plugin is translated and the folder for indexer is translated. The indexing of the German and English language works great. The search for russian language did not bring any results (нет результатов.). 
The indexed content of PDF files looks like this: 
LMS, ???????? SN ???????? ???????, ??????? ???????? ??? ???? ?????????. ??? ???? ??????? ? ??????? ?? 70 - 1,000 ??.  
The database uses utf-8.

**Comment by ste101** [comment]
Did you test pdftotext at the console?
```./pdftotext -enc UTF-8 xxx.pdf```
Maybe the encoding of the russian file is different.

**Comment by windups76** [comment]
Hello,
Thanks for the answer, but even the normal website search does not bring any result.

**Comment by ste101** [comment]
Is the encoding of the normal website content correct?

**Comment by windups76** [comment]
The encoding settings should be correct.

config.language = ru
config.locale_all = ru_RU.UTF-8
config.htmlTag_langKey = ru-RU

Your database uses utf-8. All good.

Search result example:
https://www.sn-maschinenbau.com/index.php?id=105&L=2&tx_kesearch_pi1%5Bsword%5D=https%3A%2F%2Fwww.sn-maschinenbau.com&tx_kesearch_pi1%5Bpage%5D=1&tx_kesearch_pi1%5BresetFilters%5D=0&tx_kesearch_pi1%5BsortByField%5D=&tx_kesearch_pi1%5BsortByDir%5D=

**Comment by windups76** [comment]
Der Fehler wurde behoben. Es lag nicht an ke_search, sondern am Collation Type (latin1_swedish_ci) der Datenbankfelder "title" und "content". Diese wurden auf "utf8_general_ci" geändert. Nach einer erneuten Indexierung wird alles wie gewünscht angezeigt.
mfg
