### ISSUE TITLE
Filenames aren't indexed

### ISSUE THREAD

**Issue by ThePinkOne** [teaminmedias-pluswerk/ke_search#413]
I'm using TYPO3 v. 10.4.12 and ke_search v. 3.3.1 .

Is there a way to include the file names in the index?
The names of the pages and the contents of the files are indexed, but the file names are missing.

I tried to get around that by creating a page with the CE **filelink** where the file names are listed as links. And the content of this page is not indexed either.
I also tried to index this page with a new indexer for pages and used the single page option and added the page with the filelink-CE. But it's still not indexed.

I created an index for CE and added filelink to the list. There are no errors in var/log.

**Comment by christianbltr** [comment]
File names and file contents are indexed if you use the page, tt_content or file indexer. 

If you use the page or tt_content indexer, files will get indexed if you use the "uploads" content element or if you link files in the RTE of a text element.

Note that files will get their own record in the index. So the file name is not part of the page on which the uploads element or the link has been placed.

When you set a custom file title in the metadata, that title will be indexed additionally to the file title.

Examples:
![Auswahl_035](https://user-images.githubusercontent.com/11410553/114993881-8649c380-9e9c-11eb-90ff-a3da53dc27ea.png)

![Auswahl_036](https://user-images.githubusercontent.com/11410553/114993891-8944b400-9e9c-11eb-8d8f-e53c586d0cd3.png)

![Auswahl_037](https://user-images.githubusercontent.com/11410553/114993901-8ba70e00-9e9c-11eb-8590-09ff8c6db7f9.png)

**Comment by ThePinkOne** [comment]
Thank you for the explanation. 
So because I'm using the filelink content element instead of upload or links in RTE, I can't find the files by their name, is that correct?
I'm aware that upload and RTE works fine, but in my case I need the files from the content element filelink to be indexed.

**Comment by christianbltr** [comment]
Where is the "filelink" content element defined? Is it a custom content element? 

By default ke_search only supports the "uploads" content element.

So you will need a custom indexer your the "filelink" content element or either use RTE or the "uploads" content element.

**Comment by ThePinkOne** [comment]
It's not a custom element:
https://docs.typo3.org/m/typo3/tutorial-editors/master/en-us/ContentElements/CreatingContent/Index.html
abstract 'Typical page content' 

That's why I was confused that I can't simply add it to the list of **Content element types which should be indexed (default: text,textpic,bullets,table,html,header,uploads)** in the indexer.
I assumed that the standard elements of TYPO3 can be indexed without having to write an custom indexer. If this is not the case for this element, I think it should be mentioned somewhere.

**Comment by christianbltr** [comment]
I think are talking about the same content element here and we mix up the "CType" and the label of the content element.

The content element provided by the TYPO3 is labeled "File Links" and has the CType "uploads". This content element will be indexed by ke_search which means the attached files to this content element will be indexed.

![Auswahl_038](https://user-images.githubusercontent.com/11410553/115026216-865cba00-9ec2-11eb-9c4d-21cca3c13e1d.png)

**Comment by ThePinkOne** [comment]
I'm sorry for the misunderstanding.
But that means that I still don't understand why the file names are not found in my case. If it's okay I would go into detail again to explain the problem.

In order to try out a few things and to rule out errors in the configuration of the indexer, I created an indexer for the relevant page. The indexer is for pages and I selected the relevant page in den 'Single Pages'-option in the indexer. 
That's the way it looks:
![grafik](https://user-images.githubusercontent.com/32168086/115204235-8cd47700-a0f8-11eb-9b59-aafebb39c0c9.png)
![grafik](https://user-images.githubusercontent.com/32168086/115204304-a07fdd80-a0f8-11eb-9967-3ca36cacf7a1.png)
![grafik](https://user-images.githubusercontent.com/32168086/115204377-b4c3da80-a0f8-11eb-91a2-7e68eb8cdaab.png)


After I start the indexing process only the headlines of each Ctype is indexed and the content of the pdf. The filenames are missing and don't appear when I try to find them in the search.

![grafik](https://user-images.githubusercontent.com/32168086/115205205-9a3e3100-a0f9-11eb-8430-9e51ab391e13.png)

I also forgot to mention that I use **file collections** for this page (the files are easier to handle). 
![grafik](https://user-images.githubusercontent.com/32168086/115206274-b8586100-a0fa-11eb-9406-3c76b0124ea5.png)
![grafik](https://user-images.githubusercontent.com/32168086/115206348-cad29a80-a0fa-11eb-9b21-9c242ece4915.png)
 
Because I thought that the file collections might be the problem, I also tried to write an indexer for the folder itself, so that the files are indexed there. But that didn't work either.
Thank yo so far for answering my questions. I hope you can help me to fix this.

**Comment by ThePinkOne** [comment]
Edit: I found the problem and everything works fine now.
