### ISSUE TITLE
Indexer for Introduction Package (bootstrap_package) elements

### ISSUE THREAD

**Issue by crochelt** [teaminmedias-pluswerk/ke_search#414]
It would be great if the extension provides an indexer for all the bootstrap_package elements: accordion, cards, tabs etc

**Comment by rumpfwerk** [comment]
Yes, an indexer for the BTP-elements would be nice. 
Would be interested, if somebody has an workaround.

**Comment by christianbltr** [comment]
Moved to https://github.com/tpwd/ke_search/issues/104
