### ISSUE TITLE
ke_search Filter options automated_tagging misconception

### ISSUE THREAD

**Issue by OnyxPisces** [teaminmedias-pluswerk/ke_search#421]
According to my understanding and the description of the automated_tagging function it is supposed to "**Set tag for all children of this page**", thereby **excepting the selected parent page** from that tagging. However this is not the case, as the parent page also gets tagged with the filter option.

This might be a translation issue, but I would welcome it, if the it actually did what is being described.

Meanwhile, is there any way to achieve an actual automated tagging of sub-pages with the exclusion of the parent page besides selecting all the sub-pages manually? 

Thanks

**Comment by christianbltr** [comment]
You are right, the label was wrong. This has been fixed now.

It's currently not possible to achieve an actual automated tagging of sub-pages with the exclusion of the parent page.

If you do not want to select all sub-pages manually, you could create a hook for the page indexer which removes the tag only for the parent page.
