### ISSUE TITLE
Pre-selected filter options are not retained in pagination

### ISSUE THREAD

**Issue by Aero91** [teaminmedias-pluswerk/ke_search#422]
I have encountered the following problem:
When I use pre-selected filter options the search results are displayed as expected. But when switching to another page (pagebrowser), the filter setting is lost.

TYPO3: 10.4.16, composer
Extension Version: 3.7.2

**Comment by Aero91** [comment]
Does anyone have any ideas about this problem?

**Comment by christianbltr** [comment]
I could not reproduce this in current master of ke_search in TYPO3 11 (tested with the checkbox filter).

ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
