### ISSUE TITLE
DBAL Exception when starting indexing

### ISSUE THREAD

**Issue by Aero91** [teaminmedias-pluswerk/ke_search#423]
When I want to start indexing via the Faceted Search module, I get the following error message. The indexing via scheduler seems to work. 

TYPO3: 10.4.16, composer
Extension Version: 3.7.2

![Screenshot](https://user-images.githubusercontent.com/17228305/119118009-17770180-ba2a-11eb-9a6e-fa22dcc00da2.png)

**Comment by christianbltr** [comment]
It seems that not starting point is set. 
Which indexer are you using?

**Comment by Aero91** [comment]
@christianbltr I'm using multiple page and tt_content indexers. Do I have to set a starting point manually? As I said, the scheduler tasks runs just fine.

**Comment by christianbltr** [comment]
Did you set up ke_search freshly or did you upgrade ke_search and it worked in previous versions?

You need to specify which pages you want to index in the indexer configuration as shown in the documentation in the "QuickStart" chapter. 

Starting the indexing process via backend module or scheduler should make no difference. Maybe the errors are not shown in the scheduler.

Did you check the log at <TYPO3_PROJECT_ROOT>/var/log?

**Comment by Aero91** [comment]
It's a new project which I've set up about 7 month ago. Unfortunately, I can't say if it worked in previous versions, as I've only ever used it via scheduler before. 

Okay, that's what you meant. Of course, that's all set up. I also have a working index.

I've checked the log. There's only an empty file for ke_search and TYPO3 itself.

**Comment by christianbltr** [comment]
Maybe you could try to disable all indexers and activate them one after another to find out which indexer causes the problem.

Unfortunately, without beeing able to reproduce the issue it's hard to propose a solution.

**Comment by Aero91** [comment]
Activating one at a time was a simple but good hint. I had an indexer without a starting point in a disabled folder. I had assumed that the indexer would therefore not start. But logically that is not the case.

My mistake - thanks!
