### ISSUE TITLE
Empty where clause on reindexing causing error

### ISSUE THREAD

**Issue by interojengel** [teaminmedias-pluswerk/ke_search#424]
`Uncaught TYPO3 Exception: Too few arguments to function Doctrine\DBAL\Query\QueryBuilder::where(), 0 passed in /<full_path>/typo3_src-10.4.15/typo3/sysext/core/Classes/Database/Query/QueryBuilder.php on line 649 and exactly 1 expected | ArgumentCountError thrown in file /<full_path>/typo3_src-10.4.15/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php in line 799. Requested URL: https://<our-domain>/typo3/index.php?route=%%2Fmodule%%2Fsystem%%2FtxschedulerM1&token=--AnonymizedToken--&tx_scheduler[execute][]=5`
This happens everytime on planned reindexing. Installed is ke_search 3.8.0.

**Comment by christianbltr** [comment]
I'm not sure if this is ke_search related. Could you try to delete and re-create the task?

**Comment by jcnengel** [comment]
Thanks a lot for the suggestion, but re-creating does not change a thing.

**Comment by interojengel** [comment]
Thanks a lot for the suggestion, but unfortunately re-creating the task does not change anything. Is there any way to debug this?

**Comment by christianbltr** [comment]
Do you use the console command or the scheduler task?
The scheduler task is obsolete and has been removed in current version.
Could you test the current version 4.1.0?

I'm closing this here. Feel free to open another issue at https://github.com/tpwd/ke_search/issues it is still an issue for you.
