### ISSUE TITLE
CMS Visual updates

### ISSUE THREAD

**Issue by mikestreety** [teaminmedias-pluswerk/ke_search#425]
Hey,

I've been using KE Search for a while now and it is great - but was wondering if you were open to some visual updates in the back-end?

I was about to start thinking about PRs, but didn't want to tread on any toes (or waste my time if it was something you either didn't want or were already working on).

I really appreciate the plugin and these suggestions are very superficial. If you are happy for me to submit PRs for any/all/none of them then please let me know.

The things that struck me:

## Icons

It seems the icons are slightly outdated and could utilise the TYPO3 icons system (https://typo3.github.io/TYPO3.Icons/) for things like pages, tt_news, document type (e.g. word, excel) et al. 

It would also help with visual grepping if the indexer list used the icons of the indexer itself 

e.g. 
![image](https://user-images.githubusercontent.com/354085/121021413-45ce3e00-c799-11eb-99e1-ecc97e651900.png)

## Module Navigation

This is very minor but the styles for the module navigation could be updated:

Currently:

![image](https://user-images.githubusercontent.com/354085/121021788-a5c4e480-c799-11eb-8113-f010e83c270e.png)

Info module:

![image](https://user-images.githubusercontent.com/354085/121021930-c4c37680-c799-11eb-8644-40df8632295b.png)

## Module styles

It would be nice if the general module styles were bought a bit more up-to-date with TYPO3 itself - again, i'm more than happy to have a go at this if you would like.

---

Thanks again for a great extension!

**Comment by christianbltr** [comment]
Hey,

thanks a lot for your proposal!

I would really appreciate any PRs in this area.

In fact, I realize that the design / UI in the backend is not optimal, but I did not have time enough to make improvements in this area.

So thanks in advance for any input!

**Comment by mikestreety** [comment]
@christianbltr Hey, my first pass can be found in the Pull Request above (https://github.com/teaminmedias-pluswerk/ke_search/pull/427) - would appreciate any feedback

**Comment by christianbltr** [comment]
Thank you :+1: will comment there

**Comment by christianbltr** [comment]
I opened issue https://github.com/teaminmedias-pluswerk/ke_search/issues/435 for the backend module function menu and I'm closing this one.
