### ISSUE TITLE
Display categories of item in the list search results

### ISSUE THREAD

**Issue by ManOnZeMoon** [teaminmedias-pluswerk/ke_search#426]
Hi ! All is in the question, 
i would like to display categories (ou firstcategorie) of item (news item) in the list of search results.
<f:debug>{resultrow}</f:debug> show that this categorie list is not avalaible.
Is it possible ?
thanks !!

**Comment by christianbltr** [comment]
Hi. Categories are currently not available out of the box in the resultrow. You could implement your own viewhelper and use the uid of the news item (field "orig_uid") to fetch and display the related category.
