### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by sapfeer0k** [teaminmedias-pluswerk/ke_search#433]
Hi everyone,

Do you have any plans to add a support of `postgresql`? 
If not - would you consider to merge my changes if I will add `postgresql` support by myself?

**Comment by christianbltr** [comment]
There are currently no plans to support PostgreSQL.

Since I do not have a test setup to test it, it would be hard to maintain. Maybe you could implement it in an additional extension and hook into ke_search? I would merge patches which add additional hooks.

**Comment by christianbltr** [comment]
There are currently no plans to support PostgreSQL.

Since I do not have a test setup to test it, it would be hard to maintain. Maybe you could implement it in an additional extension and hook into ke_search? I would merge patches which add additional hooks.
