### ISSUE TITLE
Exception in FE when file is missing in Workspace

### ISSUE THREAD

**Issue by medarob** [teaminmedias-pluswerk/ke_search#434]
I hope that I identified the error correctly and it's an issue with workspaces.

**Problem:**

The following error appeard in the FE after the search:

![grafik](https://user-images.githubusercontent.com/33951787/125612345-c905b30c-7bc7-4e90-814e-cd19867d7a67.png)

**From the Log:**
(1/2) #1509741911 TYPO3Fluid\Fluid\Core\ViewHelper\Exception
No file reference (sys_file_reference) was found for given UID: "9377"

Looking at the table sys_file_reference with the uid=9377 shows that this file seems to be associated with a news record in Worspaces.
![grafik](https://user-images.githubusercontent.com/33951787/125612744-d27fc84c-c6a8-439a-b0fe-c859aed74648.png)
![grafik](https://user-images.githubusercontent.com/33951787/125614228-2251076d-90ab-4f94-90fc-0e33bf2b6a60.png)
What I don't know right now why there is a "1" in the "relatedVideo" column:
![grafik](https://user-images.githubusercontent.com/33951787/125614514-75919dda-e903-44f8-9539-c33f3a06637d.png)

The news record in question (with the id 7530) has in the workspace two images with the ids "9378 - NEW Element" and "9379". There is no image with an id 9377.

Deleting the workspace news record with the id 7531 **did not** solve the problem.
Updating the reference index **did not** help either.

When I delete the image from the news record inside the workspaces module, then the error in the FE is gone.
![grafik](https://user-images.githubusercontent.com/33951787/125618637-17cdeed3-8e9e-4fc2-9f4e-a3fcf1bc1d78.png)

![grafik](https://user-images.githubusercontent.com/33951787/125618438-478faec3-dc82-48a9-af35-2ab34eecdacd.png)

So, my conslusion would be that file changes in workspace could cause the exception with ke_search, if someone searches for a searchphrase which is, for example used in a news record, which uses the file. The file change was not published in the live mode and deleting the file from the workspace module list solved the issue and ke_search worked again.

But I guess it could happen again with other files?

Tested with ke_search 3.8.1 and TYPO3 10.4.17.

**Comment by christianbltr** [comment]
Thanks, this has been fixed and will be in the next version.

Please note that the fix is in the new repository https://github.com/tpwd/ke_search
