### ISSUE TITLE
Indexer icons

### ISSUE THREAD

**Issue by mikestreety** [teaminmedias-pluswerk/ke_search#437]
One of my bullet points in #425 was about the icons. I decided not to do it as part of the overhaul to avoid too much noise in one PR. As that issue is now closed, it made sense to make it its own issues

---

## Icons

It seems the icons are slightly outdated and could utilise the TYPO3 icons system (https://typo3.github.io/TYPO3.Icons/) for things like pages, tt_news, document type (e.g. word, excel) et al.

It would also help with visual grepping if the indexer list used the icons of the indexer itself

e.g.

![image](https://user-images.githubusercontent.com/354085/125956054-03b0fe3a-3039-43a4-b8dd-7b1d7df32e74.png)

**Comment by christianbltr** [comment]
Moved to https://github.com/tpwd/ke_search/issues/108
