### ISSUE TITLE
Disable files indexer

### ISSUE THREAD

**Issue by plojewski** [teaminmedias-pluswerk/ke_search#438]
Hi,
is any possibility to exclude files indexing with tt_content and pages configurations?

**Comment by christianbltr** [comment]
For single files that's currently not possible. It's only possible for file types (e. g. doc, pdf). Or you could decide not to index files at all via the page indexer and use the file indexer where you can specify folders which you want to index.

A possible implementation for this feature would be to add a field "Include in search" for the files metadata (same as in the page properties) and check that during indexing.

**Comment by christianbltr** [comment]
see https://github.com/tpwd/ke_search/issues/20
