### ISSUE TITLE
Sorting with a multi-word search breaks

### ISSUE THREAD

**Issue by mikestreety** [teaminmedias-pluswerk/ke_search#439]
The sorting template uses a typolink (https://github.com/teaminmedias-pluswerk/ke_search/blob/master/Resources/Private/Partials/Sorting.html#L13) which means when you have a multi word search (e.g. `hello world`) Typo3 interprets this as a search for "hello" and a target of "world" - so the sorting links don't work.

In my local template I have replaced the typolink tag with an `<a href="">`

**Comment by christianbltr** [comment]
Unfortunately I could not reproduce this issue.

My test scenario:

![Auswahl_029](https://user-images.githubusercontent.com/11410553/140498353-9fb7bb71-dbf0-4f47-99bf-41b663d030b1.png)

I search for "lorem ipsum".
I clicked the "Date" link in the sort options - sorting works.

The generated link is:

```
[...]?tx_kesearch_pi1%5Bfilter_1%5D=&tx_kesearch_pi1%5BsortByDir%5D=desc&tx_kesearch_pi1%5BsortByField%5D=sortdate&tx_kesearch_pi1%5Bsword%5D=lorem%20ipsum
```

How can I reproduce the issue?

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
