### ISSUE TITLE
Exceptions / Syntax Errors on PHP < 7.4

### ISSUE THREAD

**Issue by bzgaLindner** [teaminmedias-pluswerk/ke_search#440]
Hi and big thanks for this great Extension!

On PHP < 7.4, I get an Error when updating ke_search to 4.0.0, saying:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) | ParseError thrown in file [...]/typo3conf/ext/ke_search/Classes/Domain/Repository/BaseRepository.php in line 38. 

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: syntax error, unexpected ')' | ParseError thrown in file [...]/typo3conf/ext/ke_search/Classes/Domain/Repository/BaseRepository.php in line 94. 

It also happens with other /XyzRepository.php after removing the "string" in BaseRepository.php and so on.

I guess this only hapens in PHP < 7.4, but there is no dependency on PHP 7.4 mentioned and the supported TYPO3 10.4 still supports PHP > 7.2, so this should be considered.

I am not shure if this affects also earlier versions .

Thanks for your attention!

Dominik Lindner

**Comment by christianbltr** [comment]
This has been fixed with https://github.com/tpwd/ke_search/pull/5

BTW Please use https://github.com/tpwd/ke_search/issues for further issues, thank you.
