### ISSUE TITLE
Title mit 3 Zahlen werden nicht gefunden bei news indexer

### ISSUE THREAD

**Issue by p-view** [teaminmedias-pluswerk/ke_search#441]
I have News titles like  BRT-65-723 and ART-65-3334. When i search BRT-65-723 nothings found. When iam searching ART-65-3334 i get the result. Has BRT-65-723 on more number at the end it would be found.
Any solution for this problem?

**Comment by christianbltr** [comment]
Most likely the minimum searchword length is still set to "4" (the default).

You can set it to "3" as explained here: https://docs.typo3.org/p/tpwd/ke_search/main/en-us/Configuration/SearchWordLength.html

**Comment by p-view** [comment]
thx for the hint. Would also be cool when it crawls words with "-" inside as one word.

**Comment by christianbltr** [comment]
Yes, that's true. In some cases that would be helpful. MySQL treats the dash as word separator so that's currently not possible.

I will open a feature request on https://github.com/tpwd/ke_search/issues (BTW that's the repository where ke_search is now maintained).

**Comment by christianbltr** [comment]
https://github.com/tpwd/ke_search/issues/19
