### ISSUE TITLE
Task not working due to inheriting from non-existing class

### ISSUE THREAD

**Issue by pduersteler** [teaminmedias-pluswerk/ke_search#45]
The `startIndexing` task which is available through `typo3/cli_dispatch.phpsh` is not working, as the class in `ke_search/cli/class.cli_kesearch.php` extends `t3lib_cli`, which is not existing anymore in 7 LTS. It should be extending `\TYPO3\CMS\Core\Controller\CommandLineController`.

**Comment by christianbltr** [comment]
Fixed in current master.

Will be in next version after 2.2.1

Minimun TYPO3 version raised to 7.6
