### ISSUE TITLE
Pagination translation: prev-next from fluid

### ISSUE THREAD

**Issue by zabinetta** [teaminmedias-pluswerk/ke_search#451]
fluid has already got  prev-next translations for pagination, why not use them in 
Resources/Private/Templates/Widget/Pagination.html

`<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
      xmlns:kesearch="http://typo3.org/ns/TeaminmediasPluswerk\KeSearch\ViewHelpers"
      data-namespace-typo3-fluid="true">

<f:spaceless>
<ul>
<f:if condition="{pagination.previous}">
    <li>
        <kesearch:link piVars="{page: pagination.previous}" keepPiVars="1" class="prev">{f:translate(key:'widget.pagination.previous', extensionName: 'fluid')}</kesearch:link>
    </li>
</f:if>
<f:for each="{pagination.pages}" as="page">
    <li>
        <kesearch:link piVars="{page: page}" keepPiVars="1" class="{f:if(condition: '{page} == {pagination.currentPage}', then: 'current')}">{page}</kesearch:link>
    </li>
</f:for>
<f:if condition="{pagination.next}">
    <li>
        <kesearch:link piVars="{page: pagination.next}" keepPiVars="1" class="next"> {f:translate(key:'widget.pagination.next', extensionName: 'fluid')}</kesearch:link>
    </li>
</f:if>
</ul>
</f:spaceless>`

**Comment by zabinetta** [comment]
translation could be far more flexible in resultrows, too. try:
{f:translate(key:'pagebrowserresult', extensionName: 'ke_search', arguments:{0:pagebrowser.start,1:pagebrowser.end,3:pagebrowser.total},default:'Result %s until %s of %s')}

**Comment by christianbltr** [comment]
Pagination has been reworked with https://github.com/tpwd/ke_search/pull/203
