### ISSUE TITLE
How to kill indexer intances

### ISSUE THREAD

**Issue by netbrothers-tr** [teaminmedias-pluswerk/ke_search#47]
If you run the indexer and something goes wrong it might go into an indefinite state where it's not running anymore but still recognised to be alive. When rerunning the indexer (from the command line) you'll receive this line:

`You can't start the indexer twice. Please wait while first indexer process is currently running`

What would be a method to clear the running instance? Deleting the TYPO3 temp folder and clearing all cache didn't help.

**Comment by christianbltr** [comment]
You can go to the backend module and stop it from there.

Usually you'll find a green button "start indexing" in the backend. Given the indexer did not work correctly you'll find a red button which allows you to remove the "indexer lock".

The "lock" is technically spoken an entry in the TYPO3 registry.

**Comment by netbrothers-tr** [comment]
Thank you @christianbltr for the hint. I've tested it and it works without a problem! :thumbsup:

**Comment by christianbltr** [comment]
Great, so I'm closing this issue.
