### ISSUE TITLE
Duplicate (file) index entries because of memory write buffer

### ISSUE THREAD

**Issue by mrvoss** [teaminmedias-pluswerk/ke_search#50]
`\tx_kesearch_indexer::storeInIndex()` checks if data has been indexed already by querying the `tx_kesearch_index` table (in `checkIfFile|RecordWasIndexed()`). There is a problem with that, because the data to be indexed is not written directly to the db, but buffered in memory (`$this->amountOfRecordsToSaveInMem = 500;`) and only written after 500 records have been collected. This means that if there are 500 identical entries in the buffer, all those identical entries are written to the db.

2 suggestions to fix this:

a) remove the whole memory buffering. In my tests (setting `$this->amountOfRecordsToSaveInMem = 1`), I did no notice performance loss. My suggestion, clean solution (if `prepareRecordForInsert|Update()` etc. would be refactored away).
b) include the current memory buffer in `checkIfRecordWasIndexed()` and `checkIfFileWasIndexed()` - not so nice.

**Comment by mrvoss** [comment]
Any opinion on this? Thank you!

**Comment by christianbltr** [comment]
I could reproduce this.

I would prefer your solution a) if there's no performance loss. With how many records in the index did you do the test?

**Comment by mrvoss** [comment]
I just tested again. Cleared the index and reindexed, with

a) `$this->amountOfRecordsToSaveInMem = 1`, no duplicates: 1479 records, and
b) `$this->amountOfRecordsToSaveInMem = 500`, with duplicates: 2040 / 1659 (after deleting 381 entries in the cleanup step) records:

a) took about 9 mins, 
b) took about 19 mins

My test case might be a little special because I have many files (542 without duplicates, 1136 with duplicates) which get content processed with pdftotext etc., which takes quite some time. Avoiding to repeatedly process these files (I have some that, because of this issue, get processed up to 7 times!) naturally saves a lot of time. What I want to say is that with this setup, I cannot really make a statement about the impact of removing the memory save buffer, because the file processing savings way outperform it. Maybe you (or someone else) could benchmark `$this->amountOfRecordsToSaveInMem = 1`.

Increasing the indexing speed by about 100 % (19 -> 9 mins), and in the process removing duplicate entries, should be worth a consideration in any case.

**Comment by christianbltr** [comment]
I did a test without file indexing:

22.000 news records, no file indexing

Index is empty
500 records in memory (default setting)
1. run: 198 sec. indexing time
2. run: 195 sec. indexing time

Index has been been filled before
500 records in memory (default setting)
1. run: 485 sec. indexing time

Index is empty
1 record in memory (test setting)
1. run: 205 sec. indexing time
2. run: 211 sec. indexing time

It seems that the memory buffering gives a performance gain of around 10%.

I would say we go with the removal of the memory buffering.

I think the advantages are:
- A more transparent indexing process in general
- no duplicates
- a lot faster if there are duplicates detected while indexing files

I will start a branch for this. Would you test it?

**Comment by christianbltr** [comment]
Could you please test https://github.com/teaminmedias-pluswerk/ke_search/tree/remove-memory-buffering

Note: In my test case there was no perfermance loss at all compared to to the memory buffering with 500 records.

**Comment by mrvoss** [comment]
I just tested https://github.com/teaminmedias-pluswerk/ke_search/tree/remove-memory-buffering . Works flawlessly in my setup. Ready for merge I would say :)

Thanks a lot for looking at and implementing this!

**Comment by christianbltr** [comment]
Merged with https://github.com/teaminmedias-pluswerk/ke_search/pull/59 into master, will be in next version after 2.3.0
