### ISSUE TITLE
Backend module not working

### ISSUE THREAD

**Issue by pduersteler** [teaminmedias-pluswerk/ke_search#53]
On current master, when trying to use the backend module, I receive `Fatal error: Class 'tx_kesearch_indexer' not found`.

**Comment by christianbltr** [comment]
Could test again if this is fixed with https://github.com/teaminmedias-pluswerk/ke_search/pull/54?

**Comment by christianbltr** [comment]
This issue seemed to be only the case in an environment not installed with composer.

After applying https://github.com/teaminmedias-pluswerk/ke_search/pull/54 this seems to be fixed in current master.

I tested this in a 7.6.9 installation not installed with composer.
