### ISSUE TITLE
Manual as wrong links to "real" documentation

### ISSUE THREAD

**Issue by gaumondp** [teaminmedias-pluswerk/ke_search#57]
In "further documentation" you link to http://kesearch.kennziffer.com/en/documentation.html but this produce a 404.

Good link would be https://www.typo3-macher.de/en/facetted-search-ke-search/documentation/introduction/

**Comment by christianbltr** [comment]
Thanks, has been fixed.

**Comment by gaumondp** [comment]
Great but the OpenOffice file needs also the correct link : 

https://docs.typo3.org/typo3cms/extensions/ke_search/ExtFacetedSearch/FurtherDocumentation/Index.html

**Comment by christianbltr** [comment]
Thanks, I removed that old document.

[TASK]    Remove legacy OpenOffice documention (doc/ folder) in favor of a simple README.rst as proposed in https://docs.typo3.org/typo3cms/CoreApiReference/ExtensionArchitecture/Documentation/Index.html.
