### ISSUE TITLE
News indexer: double index for tx_news type=1

### ISSUE THREAD

**Issue by zabinetta** [teaminmedias-pluswerk/ke_search#64]
Hi, it would be a good thing to have a configuration option in the news-indexer to disable indexing for news that are pages (type1). Otherwise you might get double searchresults for the news and the page.
with the best regards,
Sabine

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
