### ISSUE TITLE
Module : Limit Searchword statistics displayed

### ISSUE THREAD

**Issue by gaumondp** [teaminmedias-pluswerk/ke_search#74]
Currently the module shows search words for the last 30 days but with a site such ours, we got more than 15 000 records in less than 30 days so the display should be a bit more under control.

Maybe 30 days but 25/100 lines for each language maximum ?

**Comment by christianbltr** [comment]
Yes, right now the searchword statistic presentation is quite basic and could be improved generally. I think if you want to get deeper into the analysis of search phrases it would be a good idea to use google analytics or piwik. Of course a piwik integration is still lacking, that would be a good feature, too.

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
