### ISSUE TITLE
Limit lenght of searched phrase and ignore duplicated words

### ISSUE THREAD

**Issue by gaumondp** [teaminmedias-pluswerk/ke_search#75]
After many unsuccessful attempts by scripts to do SQL injections using KE_Search forms, our TYPO3 instance is full of this kind of searchphrase in tx_kesearch_stat_search : 

` 999999.9 union select 0x31303235343830303536,0x31303235343830303536,0x31303235343830303536 `

and also hundreds of with variations in the number of words "null" : 

`union select null,null,null,null,null,null,null,null,null,null,null,null,null,null`

Two suggestions :
1. Would it be possible to add some kind of limit to the length of what is searched and ignore if it reaches it ?
2. Ignore or throw an error message when a word is doubled ?

Thanks !

**Comment by christianbltr** [comment]
Yes, I think that would make sense. Maybe instead of throwing an error when a word is doubled, a blacklist (built-in, but extendable) could be helpful, so for example if a search phrase contains "union select null", this search request would be completely ignored.

**Comment by marvin-martian** [comment]
What you should really be doing is implementing word-stemming https://en.wikipedia.org/wiki/Stemming and stop-words https://en.wikipedia.org/wiki/Stop_words.  (Stop-words is basically your blacklist you suggested) It is used commonly for filtering search input and indexing searches.  There is a PECL stemming class for PHP here https://pecl.php.net/package/stem based on the snowball http://snowballstem.org/ stemming model.  Each language has its own stemming rules and common stop-words. MySQL has built-in stop words in its full-text search but it is very limited. http://dev.mysql.com/doc/refman/5.7/en/fulltext-stopwords.html So you will probably want to find a more comprehensive list. http://xpo6.com/list-of-english-stop-words/ Of course this would be needed for multiple languages.

Using stemming and stop-words creates quite natural searches,  I wish I had the time I would give you a hand to implement this..  :-/  Anyway I hope you take it as a pointer in the right direction, writing a good/fast search engine is a linguistic "black" art.

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
