### ISSUE TITLE
[BUGFIX] Add urldecode for logging to sys_log

### ISSUE THREAD

**Issue by Kephson** [teaminmedias-pluswerk/ke_search#76]
If there are spaces in not indexed URLs you will ger errors in backend module for sys_log table with ke_search enabled.
`$GLOBALS['BE_USER']->simplelog(urldecode($plaintextReport), 'ke_search');` in class.tx_kesearch_indexer.php will help to remove this error.

**Comment by Kephson** [comment]
Added a fork with some features/bugfixes: https://github.com/Kephson/ke_search

**Comment by christianbltr** [comment]
Please create a pull request. Thank you!

**Comment by Kephson** [comment]
Done: https://github.com/teaminmedias-pluswerk/ke_search/pull/80

**Comment by christianbltr** [comment]
Merged with https://github.com/teaminmedias-pluswerk/ke_search/pull/97
