### ISSUE TITLE
Backend TYPO3 7.6: Selection of filter in plugin is not working

### ISSUE THREAD

**Issue by onlinenow** [teaminmedias-pluswerk/ke_search#77]
Because of a breaking change in TYPO3 7.6 LTS the selection of filter in a plugin is not working. There is only the text "[SET STARTINGPOINT FIRST!]" visible. The storage pid is set in the content element.

In the file class.user_filterlist.php there are several functions to load added filters by a itemsProcFunc. They rely on a complete parent tt_content database row. Since the change the complete parent row is  not available anymore, only the table name and the uid.

To fix the problem, simply load the the parent row with a database call and use the given uid. I used the api function BackendUtility::getRecord(). Once the parent row is loaded, the selection of filter is working again.

**Comment by christianbltr** [comment]
Which versions are you referring to?
I tested this with ke_search dev-master and TYPO3 7.6.16 and I can see the filters and filter options in the plugin flexform configuration.

**Comment by onlinenow** [comment]
I am using TYPO3 7.6.15 and the latest TER version of ke_search. In a clean installation, i could not reproduce the issue as you stated. 

After investigating a bit, i found out the behaviour is caused by the compatibility6 extension i have installed ( which is needed for this installation ). This extensions comes with an own version of the TYPO3\CMS\Backend\Form\FormDataProvider\TcaFlexProcess ( problem is in the function modifyDataStructureAndDataValuesByFlexFormSegmentGroup() ) which is not fully compatible.

The question is now how do i solve this problem. Should i forward this to the compatility6 extension guys? I can also provide a PR with the small changes i made to ke_search.

**Comment by christianbltr** [comment]
If you like, you can create a PR for ke_search. 

Please include a condition so that your code is only executed if compatibility6 is installed.

**Comment by JanBartels** [comment]
@onlinenow: Please post your solution here even if it's not a PR yet. I would prepare a patch and a PR then as I have the same problem on my installations.

**Comment by onlinenow** [comment]
I created a PR for this. It does not check for a TYPO3 version but checks if the needed record row is available and if not load it.

**Comment by JanBartels** [comment]
Thanks a lot. The patch works perfectly.

**Comment by christianbltr** [comment]
fixed with https://github.com/teaminmedias-pluswerk/ke_search/pull/133
