### ISSUE TITLE
Transfer Pagebrowser Templating to Fluid

### ISSUE THREAD

**Issue by nixahnung** [teaminmedias-pluswerk/ke_search#81]
Hello,
i have transfered to templating code vom lib to fluid template,
Maybe you could take it into the repo.

[class.tx_kesearch_lib.php (renderPagebrowser).txt](https://github.com/teaminmedias-pluswerk/ke_search/files/765040/class.tx_kesearch_lib.php.renderPagebrowser.txt)

**Comment by nixahnung** [comment]
[PageBrowser.html.txt](https://github.com/teaminmedias-pluswerk/ke_search/files/765044/PageBrowser.html.txt)

**Comment by christianbltr** [comment]
Thanks for your work. Could you create a pull request?

**Comment by rowild** [comment]
Would love to see that in the core!!! Please PR!

**Comment by christianbltr** [comment]
That has been implemented in https://github.com/teaminmedias-pluswerk/ke_search/pull/183/commits/66c3a1e7c1744569d66e0787fb45574e4ea6a3ab
