### ISSUE TITLE
Indexing of fal_securedownload links breaks the indexing process

### ISSUE THREAD

**Issue by fieteboerner** [teaminmedias-pluswerk/ke_search#82]
according to number 11 of the [error log](https://gist.github.com/fieteboerner/217e98ff6bdb8226b7db658d5b4d44ee) `TYPO3\CMS\Core\Resource\ResourceStorage->getPublicUrl` is wrong.

the protected link should be generated. the indexing process stops at this point

**Comment by fieteboerner** [comment]
This error occurs only if the indexer was startet in CLI context. In BE context the indexer works fine.

**Comment by christianbltr** [comment]
Maybe the backend cli user does not have the correct permissions?

**Comment by fieteboerner** [comment]
Which permissions do you recommend?

**Comment by fieteboerner** [comment]
The indexing process stops working even if the CLI has permissions to all files.

**Comment by fieteboerner** [comment]
The problem is still there. I've closed this issue accidentally.

**Comment by christianbltr** [comment]
Could be related to
https://github.com/teaminmedias-pluswerk/ke_search/pull/70

**Comment by christianbltr** [comment]
fixed with #70
