### ISSUE TITLE
Roadmap for TYPO3 V8

### ISSUE THREAD

**Issue by akerssies** [teaminmedias-pluswerk/ke_search#84]
First of all, great search plugin. It's working great on v7 LTS.

Will this plugin be updated to work on TYPO3 v8 LTS ?
If so, is there a roadmap on when to expect support for v8 ?

**Comment by wowaTYPO3** [comment]
I'm also very interested in a working version for v8, because I wanted to use ke_search in my upcoming video training for TYPO3 8 ;)

**Comment by marcelmacasso** [comment]
Yeah, best search plugin for TYPO3, great job!
Would be great to know more about when to expect support for TYPO3 8 :)

**Comment by ghost** [comment]
Please tell us some informations about Roadmap :)

**Comment by christianbltr** [comment]
Sorry that you have to wait a little more. I do have a version which basicalliy works with 8 and will push it soon, hopefully. Please have a little more patience.

**Comment by daviian** [comment]
Any update on this issue?

**Comment by christianbltr** [comment]
I'm sorry that you have to wait a little more. Right now we must not push anything to the repo. It's not in our hands in the moment.

**Comment by akerssies** [comment]
Any news on this issue ?

**Comment by beezlebug** [comment]
Really great extension :-). +1 for a TYPO3 V8 version.

**Comment by fireonmo** [comment]
@christianbltr can you please push the update into a fork?

**Comment by christianbltr** [comment]
The security fix version 2.4.2 has been approved and released today. So the blocker is gone. I pushed the adaptions to 8.7 to master. Until now I did not test everything, Backend module, Frontend plugin, page indexing works so far.

**Comment by christianbltr** [comment]
ke_search 2.5.0 has been released today and works with 8.7.
