### ISSUE TITLE
Render the Pdf file in search results and Not showing the right search result on top

### ISSUE THREAD

**Issue by wabajwa** [teaminmedias-pluswerk/ke_search#85]
Hi, 
I am using the ke-search version `1.10.3`i know it is pretty old as i didn't updated. I am using TYPO3 6.2 and php 5.4, now i am facing two issues, may be these are the bugs in this version of ke-search or not? but i am not sure about it, as i am new to typo3. 
1. First issue is when i put the link of any pdf file in pages which are being shown in search result by `ke-search`then it also render the pdf file from inside of that page and show it as a result while it shouldn't do it. I don't know what should be done in order to remove that pdf files from the search result list.

2. `ke-search`works fine when i search any page or content in english (my english version of website) but it doesn't work fine when i switch it to german language(Default Langauage) and it shows that required result not on the top but some where down or on 2 page etc. 

If anyone have an idea about it, I would be great. Thanks

Cheers 
Bajwa

**Comment by christianbltr** [comment]
Hi, please use the current version of ke_search. If you still experience problems please open an issue again.
