### ISSUE TITLE
tt_address indexer sys_language_uid = -1

### ISSUE THREAD

**Issue by zabinetta** [teaminmedias-pluswerk/ke_search#87]
Hello together,
as tt_address records have no sys_language_uid in typo3 the sys_language_uid is set to 0 in the tt_address-indexer.
if it was set to -1, address records would be indexed for all languages - this would be a better behavior, wouldn't it?
here: class tx_kesearch_indexer_types_tt_address, line 136
`			
$customfields = array(
			    'sys_language_uid' => -1,
`
with the best regards,
Sabine

**Comment by velletti** [comment]
I would also recommend this. Shall i also create a pull request for this ?

**Comment by zabinetta** [comment]
Yes, please!

**Comment by velletti** [comment]
here we go ..

**Comment by zabinetta** [comment]
merci!
