### ISSUE TITLE
Backend Module not accessible for Non-Admin users 

### ISSUE THREAD

**Issue by onlinenow** [teaminmedias-pluswerk/ke_search#89]
If you configure the access of the backend module for non-admin users, they will get the message to select a page even if the page with the records was selected.

Reason for this is a wrong api call in TeaminmediasPluswerk\KeSearch\Controller\BackendModuleController in the initializeAction function. The parameter for the the call 

`$this->perms_clause = $this->getBackendUser()->getPagePermsClause($this->id); `

is wrong. The function getPagePermsClause ( in TYPO3\CMS\Core\Authentication\BackendUserAuthentication ) does not take a page uid as parameter. The call should be:

`$this->perms_clause = $this->getBackendUser()->getPagePermsClause(1);`

The value 1 means show is allowed. There are more access rights defined there. Check the comment of getPagePermsClause.

The access would work at the moment if you put the ke_search records on the page with the uid 1. But thats not always the case.

**Comment by infabo** [comment]
well analyzed. the bug seems to be in for one year now. wow. really wow.

**Comment by a-r-m-i-n** [comment]
Thanks for figuring this out!
