### ISSUE TITLE
BUG: Search with Sphinx not working

### ISSUE THREAD

**Issue by ghost** [teaminmedias-pluswerk/ke_search#90]
Hello,

I'm premium member of ke_search and I want to use Sphinx for searching. I have installed sphinx on the customer server and enable it in the settings and configure the paths. The indexer worked very well.

But when I try to search I always get "No Results found". When I deactivate Sphinx and search then, all works correct. So it seems a problem with ke_search and sphinx.

Can u help here ?

**Comment by christianbltr** [comment]
Hi. Please contact me directly via https://www.typo3-macher.de/facettierte-suche-ke-search/kontakt/ or mail.

**Comment by ghost** [comment]
Done.
