### ISSUE TITLE
Call to undefined method TYPO3\CMS\Core\Messaging\FlashMessage::render()

### ISSUE THREAD

**Issue by georgringer** [teaminmedias-pluswerk/ke_search#94]
Calling the indexer will lead to the error `Call to undefined method TYPO3\CMS\Core\Messaging\FlashMessage::render()` in 8.7.

I guess the cause is https://docs.typo3.org/typo3cms/extensions/core/8-dev/Changelog/8.0/Breaking-72438-RemoveDeprecatedCodeFromFlashMessage.html

**Comment by Scunkaneli** [comment]
Hey there,

are you sure you are using the latest version? No problems here on CMS 8.7.1, PHP 7.1.4 and newest ke_search (2.4.2 from **github**)

**Comment by a-r-m-i-n** [comment]
I'm able to reconstruct this issue. It just occure, if an error during indexing occured.
